/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.xisemele.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.MissingResourceException;
import net.sf.xisemele.exception.XisemeleException;

public class XisemeleExceptionEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 net.sf.xisemele.exception.XisemeleException.formatMessage(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Object[] objectArray0 = new Object[5];
      XisemeleException xisemeleException0 = null;
      try {
        xisemeleException0 = new XisemeleException("'MMCUJIFkOBBpx%{.%", objectArray0);
        fail("Expecting exception: MissingResourceException");
      } catch(MissingResourceException e) {
        /*
         * Can't find resource for bundle java.util.PropertyResourceBundle, key 'MMCUJIFkOBBpx%{.%
         */
      }
  }
}
