/*
 * This file was automatically generated by EvoSuite
 */

package osa.ora.server.client.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class AboutDialogEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
