/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.action;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.action.UpdateReminderQueryAction;
import org.junit.BeforeClass;

public class UpdateReminderQueryActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpdateReminderQueryAction updateReminderQueryAction0 = new UpdateReminderQueryAction();
      assertNotNull(updateReminderQueryAction0);
  }
}
