/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.wiki.engines.mediawiki.matchers;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.wiki.engines.mediawiki.matchers.PortletURLMatcher;
import javax.portlet.PortletURL;
import org.junit.BeforeClass;

public class PortletURLMatcherEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PortletURLMatcher portletURLMatcher0 = null;
      try {
        portletURLMatcher0 = new PortletURLMatcher((PortletURL) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
