/*
 * This file was automatically generated by EvoSuite
 */

package com.imsmart.misc;

import org.junit.Test;
import static org.junit.Assert.*;
import com.imsmart.misc.MProperties;
import org.junit.BeforeClass;

public class MPropertiesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MProperties mProperties0 = MProperties.getInstance();
      String string0 = mProperties0.getPropertyValue("DDJyhYBg7@iQL");
      assertNull(string0);
  }
}
