/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.dao.shard;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.dao.shard.ShardUtil;
import org.junit.BeforeClass;

public class ShardUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShardUtil shardUtil0 = new ShardUtil();
  }
}
