/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jsecurity.aop.MethodInvocation;
import org.jsecurity.authz.aop.RoleAnnotationMethodInterceptor;
import org.junit.BeforeClass;

public class AuthorizingAnnotationMethodInterceptorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RoleAnnotationMethodInterceptor roleAnnotationMethodInterceptor0 = new RoleAnnotationMethodInterceptor();
      try {
        roleAnnotationMethodInterceptor0.invoke((MethodInvocation) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * method argument cannot be null
         */
      }
  }
}
