/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jsecurity.authz.aop.GuestAnnotationMethodInterceptor;
import org.junit.BeforeClass;

public class GuestAnnotationMethodInterceptorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GuestAnnotationMethodInterceptor guestAnnotationMethodInterceptor0 = new GuestAnnotationMethodInterceptor();
  }
}
