/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.annotation.Annotation;
import org.jsecurity.authz.AuthorizationException;
import org.jsecurity.authz.aop.RoleAnnotationHandler;
import org.junit.BeforeClass;

public class RoleAnnotationHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RoleAnnotationHandler roleAnnotationHandler0 = new RoleAnnotationHandler();
      roleAnnotationHandler0.assertAuthorized((Annotation) null);
  }
}
