/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jsecurity.authz.aop.RoleAnnotationMethodInterceptor;
import org.junit.BeforeClass;

public class RoleAnnotationMethodInterceptorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RoleAnnotationMethodInterceptor roleAnnotationMethodInterceptor0 = new RoleAnnotationMethodInterceptor();
  }
}
