/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class AdvLexemEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AdvLexem advLexem0 = new AdvLexem("dh(Sctu]@+2Xz", (byte)6, (byte)1, (byte)0, 0, (int) (byte)1);
      assertEquals(1, advLexem0.column);
      assertEquals((byte)1, advLexem0.lcategory);
      assertEquals((byte)6, advLexem0.code);
      assertEquals(0, advLexem0.line);
      assertEquals((byte)0, advLexem0.hcategory);
  }
}
