/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.common.lucene;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.statsbiblioteket.summa.common.lucene.Inspect;
import org.junit.BeforeClass;

public class InspectEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Inspect.dumpMemory();
  }

  @Test
  public void test1()  throws Throwable  {
      Inspect inspect0 = new Inspect("C|(olectorPoolFator");
      assertNotNull(inspect0);
      assertEquals("247/284MB used", inspect0.getMem());
  }
}
