/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.documentlibrary.model.impl.DLSyncImpl;
import org.evosuite.testcase.TestCaseExecutor;
import org.junit.BeforeClass;

public class DLSyncImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DLSyncImpl dLSyncImpl0 = null;
      try {
        dLSyncImpl0 = new DLSyncImpl();
        fail("Expecting exception: ExceptionInInitializerError");
      } catch(ExceptionInInitializerError e) {
      }
  }
}
