/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.Combat;
import lotus.core.Player;
import org.junit.BeforeClass;

public class CombatEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Combat combat0 = new Combat((Player) null, (Player) null);
      assertNotNull(combat0);
  }
}
