/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.CardCollection;
import lotus.core.Game;
import lotus.core.Player;
import lotus.core.interfaces.UserInterface;
import org.evosuite.testcase.CodeUnderTestException;
import org.junit.BeforeClass;

public class GameEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Player player0 = Game.getNonPlayingPlayer();
      assertNull(player0);
  }

  @Test
  public void test1()  throws Throwable  {
      Player player0 = Game.getOtherPlayer((Player) null);
      assertNull(player0);
  }

  @Test
  public void test2()  throws Throwable  {
      Game.getPlayingPlayer();
  }
}
