/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.deploy.auto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.deploy.auto.HookAutoDeployListener;
import org.junit.BeforeClass;

public class HookAutoDeployListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HookAutoDeployListener hookAutoDeployListener0 = null;
      try {
        hookAutoDeployListener0 = new HookAutoDeployListener();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.util.PropsValues
         */
      }
  }
}
