/*
 * This file was automatically generated by EvoSuite
 */

package corina.print;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.print.EmptyLine;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import org.junit.BeforeClass;

public class EmptyLineEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      EmptyLine emptyLine0 = new EmptyLine();
      int int0 = emptyLine0.height((Graphics) null);
      assertEquals(18, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      EmptyLine emptyLine0 = new EmptyLine();
      PageFormat pageFormat0 = new PageFormat();
      emptyLine0.print((Graphics) null, pageFormat0, (-328.37357F));
      assertEquals(648.0, pageFormat0.getImageableHeight(), 0.01D);
  }
}
