/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.common.filter.object;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.statsbiblioteket.summa.common.configuration.Configuration;
import dk.statsbiblioteket.summa.support.enrich.MARCXMLCopyFilter;
import org.junit.BeforeClass;

public class MARCObjectFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        Configuration.getSystemConfiguration("t", true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class dk.statsbiblioteket.summa.common.configuration.Configuration
         */
      }
  }
}
