/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.selector;

import org.junit.Test;
import static org.junit.Assert.*;
import org.exolab.jms.selector.Divide;
import org.exolab.jms.selector.Expression;
import org.junit.BeforeClass;

public class DivideEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Divide divide0 = new Divide((Expression) null, (Expression) null);
      assertNotNull(divide0);
  }
}
