/*
 * This file was automatically generated by EvoSuite
 */

package fr.unice.gfarce.interGraph;

import org.junit.Test;
import static org.junit.Assert.*;
import fr.unice.gfarce.interGraph.CreerUneFormationAction;
import fr.unice.gfarce.interGraph.FenetrePrincipale;
import fr.unice.gfarce.main.Controler;
import org.junit.BeforeClass;

public class CreerUneFormationActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CreerUneFormationAction creerUneFormationAction0 = new CreerUneFormationAction((FenetrePrincipale) null, "ToolTipText", (Controler) null);
      assertEquals(true, creerUneFormationAction0.isEnabled());
  }
}
