/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.im;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.im.YMConnector;
import org.junit.BeforeClass;

public class YMConnectorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      YMConnector.disconnect();
  }
}
