/*
 * This file was automatically generated by EvoSuite
 */

package org.jcvi.jillion.trace.sff;

import org.junit.Test;
import static org.junit.Assert.*;

public class DefaultSFFCommonHeaderDecoderEvoSuiteTest {

}
