/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.complextype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.complextype.CurAmt_Type;

public class CurAmt_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CurAmt_Type curAmt_Type0 = new CurAmt_Type();
      curAmt_Type0.equals((Object) null);
  }
}
