/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.complextype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.complextype.InvoicePremium_Type;

public class InvoicePremium_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InvoicePremium_Type invoicePremium_Type0 = new InvoicePremium_Type();
      invoicePremium_Type0.equals((Object) null);
  }
}
