/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.client.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import dsachat.client.gui.InternalChatFrame;
import dsachat.client.gui.MainFrame;
import org.junit.BeforeClass;

public class InternalChatFrameEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InternalChatFrame internalChatFrame0 = null;
      try {
        internalChatFrame0 = new InternalChatFrame((MainFrame) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
