/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.security.auth;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.security.auth.BasicAuthHeaderAutoLogin;
import org.junit.BeforeClass;

public class BasicAuthHeaderAutoLoginEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BasicAuthHeaderAutoLogin basicAuthHeaderAutoLogin0 = new BasicAuthHeaderAutoLogin();
      String string0 = basicAuthHeaderAutoLogin0.getAuthType();
      assertEquals("BASIC", string0);
  }
}
