/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.security.auth;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.security.auth.NtlmAutoLogin;
import org.junit.BeforeClass;

public class NtlmAutoLoginEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      NtlmAutoLogin ntlmAutoLogin0 = new NtlmAutoLogin();
      assertNotNull(ntlmAutoLogin0);
  }
}
