/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.security.auth;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.bean.BeanLocatorException;
import com.liferay.portal.security.auth.OpenSSOAutoLogin;
import java.util.Locale;
import org.junit.BeforeClass;

public class OpenSSOAutoLoginEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenSSOAutoLogin openSSOAutoLogin0 = new OpenSSOAutoLogin();
      Locale locale0 = Locale.ITALY;
      try {
        openSSOAutoLogin0.addUser(1779L, (String) null, (String) null, (String) null, (String) null, locale0);
        fail("Expecting exception: BeanLocatorException");
      } catch(BeanLocatorException e) {
        /*
         * BeanLocator has not been set
         */
      }
  }
}
