/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.security.auth;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.security.auth.PortalSessionAuthVerifier;
import org.junit.BeforeClass;

public class PortalSessionAuthVerifierEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PortalSessionAuthVerifier portalSessionAuthVerifier0 = new PortalSessionAuthVerifier();
      String string0 = portalSessionAuthVerifier0.getAuthType();
      assertEquals("PortalSessionAuthVerifier", string0);
  }
}
