/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.taglib.portlet;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.taglib.portlet.ResourceURLTag;
import org.junit.BeforeClass;

public class ResourceURLTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ResourceURLTag resourceURLTag0 = new ResourceURLTag();
      String string0 = resourceURLTag0.getLifecycle();
      assertEquals("RESOURCE_PHASE", string0);
  }
}
