/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.utils.PdfVersionUtility;

public class PdfVersionUtilityEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PdfVersionUtility pdfVersionUtility0 = new PdfVersionUtility();
      assertNotNull(pdfVersionUtility0);
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        PdfVersionUtility.getVersions();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        PdfVersionUtility.getVersionsList();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
