/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.data.logging.protobuf;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.data.logging.protobuf.LoggingEventWrapperProtobufCodec;
import org.junit.BeforeClass;

public class LoggingEventWrapperProtobufCodecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoggingEventWrapperProtobufCodec loggingEventWrapperProtobufCodec0 = new LoggingEventWrapperProtobufCodec();
  }
}
