/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.orb;

import org.junit.Test;
import static org.junit.Assert.*;
import java.rmi.RemoteException;
import org.exolab.jms.client.net.SharedORB;
import org.exolab.jms.net.orb.ORB;
import org.exolab.jms.net.orb.RegistryService;
import org.junit.BeforeClass;

public class RegistryServiceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SharedORB sharedORB0 = (SharedORB)SharedORB.getInstance();
      RegistryService registryService0 = null;
      try {
        registryService0 = new RegistryService((ORB) sharedORB0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'uri' is null
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      RegistryService registryService0 = null;
      try {
        registryService0 = new RegistryService((ORB) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'orb' is null
         */
      }
  }
}
