/*
 * This file was automatically generated by EvoSuite
 */

package db;

import org.junit.Test;
import static org.junit.Assert.*;
import db.HighscoreTest;
import org.junit.BeforeClass;

public class HighscoreTestEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HighscoreTest highscoreTest0 = new HighscoreTest();
  }
}
