/*
 * This file was automatically generated by EvoSuite
 */

package db;

import org.junit.Test;
import static org.junit.Assert.*;
import db.UserTest;
import org.junit.BeforeClass;

public class UserTestEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UserTest userTest0 = new UserTest();
  }
}
