/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.beanbin.data.ejb3.dao.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.persistence.EntityManager;
import javax.persistence.JoinColumn;
import net.sourceforge.beanbin.BeanBinException;
import net.sourceforge.beanbin.command.RemoveAll;
import net.sourceforge.beanbin.data.ejb3.dao.transaction.RemoveAllAction;
import org.junit.BeforeClass;

public class RemoveAllActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = JoinColumn.class;
      RemoveAll removeAll0 = new RemoveAll(class0);
      RemoveAllAction removeAllAction0 = new RemoveAllAction(removeAll0);
      // Undeclared exception!
      try {
        removeAllAction0.execute((EntityManager) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
