/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.Graphics;
import org.junit.BeforeClass;

public class MapMiniPaneEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MapMiniPane mapMiniPane0 = new MapMiniPane();
      mapMiniPane0.paint((Graphics) null);
  }
}
