/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.junit.BeforeClass;

public class MapManagerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MapManager mapManager0 = null;
      try {
        mapManager0 = new MapManager("H(NK!%%");
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
        /*
         * H(NK!%% (No such file or directory)
         */
      }
  }
}
