/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import org.junit.BeforeClass;

public class MapTileEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MapTile mapTile0 = new MapTile("Uu]FfuJ+3P8");
      assertNotNull(mapTile0);
  }
}
