/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util.bridges.jsf.sun;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.bridges.jsf.sun.LiferayRenderKitFactoryImpl;
import org.junit.BeforeClass;

public class LiferayRenderKitFactoryImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LiferayRenderKitFactoryImpl liferayRenderKitFactoryImpl0 = new LiferayRenderKitFactoryImpl();
      assertNotNull(liferayRenderKitFactoryImpl0);
  }
}
