/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util.bridges.jsf.sun;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.bridges.jsf.sun.LiferayRenderKitImpl;
import java.io.StringWriter;
import java.io.Writer;
import org.junit.BeforeClass;

public class LiferayRenderKitImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LiferayRenderKitImpl liferayRenderKitImpl0 = new LiferayRenderKitImpl();
      StringWriter stringWriter0 = new StringWriter(263);
      // Undeclared exception!
      try {
        liferayRenderKitImpl0.createResponseWriter((Writer) stringWriter0, "", "");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
