/*
 * This file was automatically generated by EvoSuite
 */

package com.mentorgen.tools.util.profile;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mentorgen.tools.util.profile.Clear;
import org.junit.BeforeClass;

public class ClearEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Clear clear0 = new Clear();
  }
}
