/*
 * This file was automatically generated by EvoSuite
 */

package com.mentorgen.tools.util.profile;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mentorgen.tools.util.profile.Client;
import org.junit.BeforeClass;

public class ClientEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Client client0 = new Client();
      assertNotNull(client0);
  }

  @Test
  public void test1()  throws Throwable  {
      Client.help();
  }
}
