/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.shopping.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.shopping.model.ShoppingCouponConstants;
import org.junit.BeforeClass;

public class ShoppingCouponConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShoppingCouponConstants shoppingCouponConstants0 = new ShoppingCouponConstants();
  }
}
