/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.shopping.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.shopping.model.ShoppingOrderConstants;
import org.junit.BeforeClass;

public class ShoppingOrderConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShoppingOrderConstants shoppingOrderConstants0 = new ShoppingOrderConstants();
  }
}
