/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.shopping.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.shopping.model.ShoppingCategoryConstants;
import org.junit.BeforeClass;

public class ShoppingCategoryConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShoppingCategoryConstants shoppingCategoryConstants0 = new ShoppingCategoryConstants();
  }
}
