/*
 * This file was automatically generated by EvoSuite
 */

package org.gudy.azureus2.cl;

import org.junit.Test;
import static org.junit.Assert.*;
import org.gudy.azureus2.cl.Main;
import org.junit.BeforeClass;

public class MainEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Main main0 = new Main();
      assertNotNull(main0);
  }
}
