/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.net.magneturi.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class MagnetURIHandlerClientEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
