/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.servlet.http.HttpServletRequest;
import org.jsecurity.web.SavedRequest;
import org.junit.BeforeClass;

public class SavedRequestEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SavedRequest savedRequest0 = null;
      try {
        savedRequest0 = new SavedRequest((HttpServletRequest) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
