/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.googleapps.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.googleapps.GUser;
import com.liferay.portal.kernel.googleapps.comparator.GUserFirstNameComparator;
import org.junit.BeforeClass;

public class GUserFirstNameComparatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GUserFirstNameComparator gUserFirstNameComparator0 = new GUserFirstNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setFirstName("?B");
      int int0 = gUserFirstNameComparator0.compare(gUser0, gUser0);
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      GUser gUser0 = new GUser();
      GUserFirstNameComparator gUserFirstNameComparator0 = new GUserFirstNameComparator(false);
      gUser0.setFirstName("?B");
      int int0 = gUserFirstNameComparator0.compare(gUser0, gUser0);
      assertEquals(0, int0);
  }
}
