/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.util.MimeTypesImpl;
import org.junit.BeforeClass;

public class MimeTypesImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MimeTypesImpl mimeTypesImpl0 = null;
      try {
        mimeTypesImpl0 = new MimeTypesImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.util.PropsValues
         */
      }
  }
}
