/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.asset.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.asset.util.DefaultAssetEntryValidator;
import org.junit.BeforeClass;

public class DefaultAssetEntryValidatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultAssetEntryValidator defaultAssetEntryValidator0 = new DefaultAssetEntryValidator();
  }
}
