from openai import OpenAI, APIConnectionError
from config import DEEPSEEK_API_KEY
import requests
import json
import pandas as pd
import time
import os
import re
import httpx 
import javalang

input_template = """
# Focal Method
```java
{focal_method}
```

# Test Prefix
```java
{prefix}
```
"""

system_prompt = '''
You are a Java Mutation Testing Assertion Expert, specialized in generating assertions that **precisely detect code defects**.

【Core Task】
Generate an assertion for the given Java method and test context.
1. Must compile (syntactically correct)
2. Must pass in the original correct version
3. Must fail in at least one defective mutant
4. Try to kill as many mutants as possible

【Thinking Path】
1. **Analyze Focal Method**: Understand the logic, return values, side effects, and boundary conditions. Identify "Mutatable Points" (conditional jumps, arithmetic operations, loop boundaries) where bugs often hide.
2. **Trace Test Context**: Identify the object state and method arguments in `test_prefix`. Locate the call to `focal_method`.
3. **Lock Target**: 
   - If the method returns a value, assert on that value.
   - If the method is void, assert on the side effects (state changes in the object).
4. **Design Strong Assertion**: 
   - Avoid weak assertions like `assertNotNull`. 
   - Use specific values from the `test_prefix` to verify exact outcomes.
   - Example: If `focal_method` adds 1 to input 5, assert `assertEquals(6, result)`, NOT `assertTrue(result > 0)`.
   - Consider edge cases: empty lists, null inputs, zero values.

【Strict Constraints】
1. **Target Precision**: Never assert variables generated by other unrelated methods at the end of `test_prefix`. Only focus on the product of `focal_method`.
2. **API Caution**: Do not fabricate non-existent methods (e.g. `getResult()`) unless you are sure it is part of the standard library.
3. **Format**: Please wrap the assertion statement in a Markdown code block, i.e., ```java ... ```. You may optionally include a `<think>...</think>` block before the code block to reason about the mutation.
4. **Compilability**: Variables must already exist; floating point comparisons need delta; numeric suffixes must be accurate.

【Input Format】
You will receive:
1. focal_method: The original correct Java method, possibly with comments
2. test_prefix: Test context (initialized objects and parameters)

【Output Requirements】
1. Output a compilable JUnit assertion statement wrapped in a Java code block.
2. Prefer assertEquals / assertArrayEquals / assertThrows / assertNotEquals.
3. If asserting floating point, provide delta; if verifying exception, use assertThrows.
4. The assertion should distinguish at least one typical mutation (arithmetic replacement, condition reversal, constant return, off-by-one, missing null handling).
'''


data_path = "/home/ubuntu/myren/SF110/qwen_test.json"
with open(data_path,'r',encoding='utf-8') as f:
    data = json.load(f)

results = []

client = OpenAI(
    api_key=DEEPSEEK_API_KEY, 
    base_url="https://api.deepseek.com",
    timeout=60.0
)

success_count = 0
failed_count = 0
skipped_count = 0
SAVE_INTERVAL = 100  # 每处理 10 条保存一次

# 处理所有数据项
id = 0
for i in range(len(data)):
    print(f"Processing item {i+1}/{len(data)}")
    #  添加过滤逻辑
    focal_method = data[i]['focal_method']
    
    if (i + 1) % SAVE_INTERVAL == 0:
        with open("result_sf110.json", 'w', encoding='utf-8') as f:
            json.dump(results, f, ensure_ascii=False, indent=4)
        print(f" 进度已保存 ({i+1}/{len(data)})")
    try:
        input_text = input_template.format(focal_method=data[i]['focal_method'], prefix=data[i]['prefix'])
        full_user_content = (
            system_prompt.strip() 
            + "\n\n" 
            + input_text.strip() 
            + " You FIRST think about the reasoning process as an internal monologue and then provide the final answer. The reasoning process MUST BE enclosed within <think> </think> tags. The final answer MUST BE a single line of Java code inside a java code block.\n\nResponse:"
        )
        messages = [
                {"role": "user", "content": full_user_content}
        ]
        
        # 添加重试机制
        max_retries = 3
        retry_delay = 1
        
        for attempt in range(max_retries):
            try:
                # 使用流式传输
                response = client.chat.completions.create(
                    model="deepseek-chat",
                    messages=messages,
                    temperature = 0.0,
                    stream=True
                    # response_format={'type': 'json_object'}  # Removed JSON enforcement to match training format
                )
                
                # 收集流式响应
                full_response = ""
                for chunk in response:
                    if chunk.choices[0].delta.content is not None:
                        full_response += chunk.choices[0].delta.content  
                
                # 检查响应是否为空
                if not full_response.strip():
                    raise ValueError("Received empty response from API")
                
                # 清理响应内容（移除可能的前后空白字符）
                full_response = full_response.strip()
                
                # 解析响应：提取代码块
                extracted_answer = full_response
                # 尝试提取Java代码块
                code_match = re.search(r"```java\s*(.*?)\s*```", full_response, re.DOTALL)
                if code_match:
                    extracted_answer = code_match.group(1).strip()
                else:
                    # 移除可能的 <think> 块
                    extracted_answer = re.sub(r"<think>.*?</think>", "", extracted_answer, flags=re.DOTALL).strip()
                    # 移除可能的其他 markdown 标记
                    extracted_answer = extracted_answer.replace("```", "").strip()

                data[i]["status"] = "success"
                data[i]["ds_generates"] = [extracted_answer] # Wrap in list to maintain compatibility
                success_count += 1
                data[i]['id'] = id
                id += 1
                results.append(data[i])
                break
                
            except APIConnectionError as e:
                if attempt < max_retries - 1:
                    print(f"  Attempt {attempt + 1} failed: {e}")
                    print(f"  Retrying in {retry_delay} seconds...")
                    time.sleep(retry_delay)
                    retry_delay *= 2
                else:
                    print(f"  Failed after {max_retries} attempts.")
                    data[i]["status"] = "failed"
                    data[i]["ds_generates"] = []
                    failed_count += 1
            # removed specific json error handling
            except Exception as e:
                print(f"  Unexpected error: {e}")
                data[i]["status"] = "failed"
                data[i]["ds_generates"] = []
                failed_count += 1
                break
        
        # 添加延迟避免触发限流
        time.sleep(0.5)
        
    except Exception as e:
        print(f"Error processing item {i}: {e}")
        failed_count += 1
        continue

client.close()

with open('result_sf110.json','w',encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=4)

print(f"Processing completed. Success: {success_count}, Failed: {failed_count}")