/*
 * This file was automatically generated by EvoSuite
 */

package simulator.SA;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import simulator.SA.GridGenerator;

public class GridGeneratorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GridGenerator gridGenerator0 = null;
      try {
        gridGenerator0 = new GridGenerator((-1), 0);
        fail("Expecting exception: ArithmeticException");
      } catch(ArithmeticException e) {
      }
  }
}
