/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.messaging;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.repository.model.FileVersion;
import com.liferay.portlet.documentlibrary.messaging.ImageProcessorMessageListener;
import org.junit.BeforeClass;

public class ImageProcessorMessageListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ImageProcessorMessageListener imageProcessorMessageListener0 = new ImageProcessorMessageListener();
      try {
        imageProcessorMessageListener0.generate((FileVersion) null, (FileVersion) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
