/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_1_0.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_1_0.util.JournalTemplateTable;
import org.junit.BeforeClass;

public class JournalTemplateTableEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JournalTemplateTable journalTemplateTable0 = new JournalTemplateTable();
  }
}
