/*
 * This file was automatically generated by EvoSuite
 */

package corina.platform;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.platform.Macintosh;
import corina.ui.CorinaAction;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class MacintoshEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        Macintosh.registerAboutHandler((CorinaAction) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        Macintosh.registerPrefsHandler((Runnable) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Macintosh macintosh0 = new Macintosh();
      assertNotNull(macintosh0);
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        Macintosh.registerQuitHandler((Runnable) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
