/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.search.lucene;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.search.lucene.IndexAccessorImpl;
import org.junit.BeforeClass;

public class IndexAccessorImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IndexAccessorImpl indexAccessorImpl0 = null;
      try {
        indexAccessorImpl0 = new IndexAccessorImpl(3L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.kernel.search.SearchEngineUtil
         */
      }
  }
}
