/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.basetypes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.basetypes.IFXHexBinary;

public class IFXHexBinaryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IFXHexBinary iFXHexBinary0 = new IFXHexBinary();
  }
}
