/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.management.jmx;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.management.jmx.ListMBeansAction;
import org.junit.BeforeClass;

public class ListMBeansActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ListMBeansAction listMBeansAction0 = new ListMBeansAction("");
      assertNotNull(listMBeansAction0);
  }
}
