/*
 * This file was automatically generated by EvoSuite
 */

package jaw.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import jaw.gui.ProcessarEntidadesTree;
import org.junit.BeforeClass;

public class ProcessarEntidadesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ProcessarEntidadesTree processarEntidadesTree0 = new ProcessarEntidadesTree();
  }
}
