/*
 * This file was automatically generated by EvoSuite
 */

package ghm.follow.nav;

import org.junit.Test;
import static org.junit.Assert.*;
import ghm.follow.FollowApp;
import ghm.follow.nav.PreviousTab;
import org.junit.BeforeClass;

public class PreviousTabEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PreviousTab previousTab0 = new PreviousTab((FollowApp) null);
      assertEquals(true, previousTab0.isEnabled());
  }
}
