/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw.bundle.server.plugins.rest.resources;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.mfw.bundle.server.plugins.rest.resources.BMRequestResource;
import org.junit.BeforeClass;

public class BMRequestResourceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BMRequestResource bMRequestResource0 = null;
      try {
        bMRequestResource0 = new BMRequestResource();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class fi.vtt.noen.mfw.bundle.server.plugins.rest.resources.BMRequestResource
         */
      }
  }
}
