/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.image;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.image.DatabaseHook;
import org.junit.BeforeClass;

public class BaseHookEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatabaseHook databaseHook0 = new DatabaseHook();
  }
}
