/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core.card;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.card.Instant;
import org.junit.BeforeClass;

public class InstantEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Instant instant0 = new Instant();
  }
}
