/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.share.hero;

import org.junit.Test;
import static org.junit.Assert.*;
import dsachat.share.hero.Spell;
import org.junit.BeforeClass;

public class SpellEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Spell spell0 = new Spell("Xe|Yg<!;2^S?*", (-798), "Xe|Yg<!;2^S?*");
  }
}
