/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.support.lucene;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.statsbiblioteket.summa.support.lucene.LuceneUtil;
import org.junit.BeforeClass;

public class LuceneUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LuceneUtil luceneUtil0 = new LuceneUtil();
      assertNotNull(luceneUtil0);
  }
}
