/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class BezierSplineEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      double[] doubleArray0 = new double[13];
      BezierSpline bezierSpline0 = new BezierSpline(doubleArray0, 2);
      double[] doubleArray1 = bezierSpline0.generate();
      assertFalse(doubleArray1.equals(doubleArray0));
  }

  @Test
  public void test1()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      BezierSpline bezierSpline0 = new BezierSpline(doubleArray0, 86);
      double[] doubleArray1 = bezierSpline0.generate();
      assertFalse(doubleArray0.equals(doubleArray1));
  }
}
