/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.business.listeners.mediators;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.business.listeners.mediators.TreeMediator;
import org.pdfsam.guiclient.gui.frames.JMainFrame;

public class TreeMediatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TreeMediator treeMediator0 = new TreeMediator((JMainFrame) null);
      assertNotNull(treeMediator0);
  }
}
