/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.beanbin.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.beanbin.BeanBinException;
import net.sourceforge.beanbin.aop.MixinBlob;
import org.junit.BeforeClass;

public class MixinBlobEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = MixinBlob.class;
      MixinBlob mixinBlob0 = new MixinBlob();
      mixinBlob0.mix(class0);
  }
}
