/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.lagoon.core;

import org.junit.Test;
import static org.junit.Assert.*;
import nu.staldal.lagoon.producer.XSLTransformer;
import org.junit.BeforeClass;

public class TransformEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XSLTransformer xSLTransformer0 = new XSLTransformer();
  }
}
