/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.documentlibrary.model.DLSyncConstants;
import org.junit.BeforeClass;

public class DLSyncConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DLSyncConstants dLSyncConstants0 = new DLSyncConstants();
  }
}
