/*
 * This file was automatically generated by EvoSuite
 */

package com.browsersoft.jaas;

import org.junit.Test;
import static org.junit.Assert.*;
import com.browsersoft.jaas.AACSUserPrincipal;
import org.junit.BeforeClass;

public class AACSUserPrincipalEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AACSUserPrincipal aACSUserPrincipal0 = new AACSUserPrincipal("");
  }
}
