/*
 * This file was automatically generated by EvoSuite
 */

package com.soops.CEN4010.JMCA.JParser.xmlParser;

import org.junit.Test;
import static org.junit.Assert.*;
import com.soops.CEN4010.JMCA.JParser.xmlParser.Selection;
import com.soops.CEN4010.JMCA.JParser.xmlParser.XMLParser;
import org.junit.BeforeClass;

public class SelectionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Selection selection0 = new Selection((XMLParser) null);
      selection0.closeState((String) null);
  }

  @Test
  public void test1()  throws Throwable  {
      Selection selection0 = new Selection((XMLParser) null);
      selection0.processState("");
  }
}
