/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.core.speedmanager.impl.v2;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.core.speedmanager.impl.SpeedManagerAlgorithmProviderAdapter;
import com.aelitis.azureus.core.speedmanager.impl.v2.SpeedManagerAlgorithmProviderV2;
import org.junit.BeforeClass;

public class SpeedManagerAlgorithmProviderV2EvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SpeedManagerAlgorithmProviderV2 speedManagerAlgorithmProviderV2_0 = null;
      try {
        speedManagerAlgorithmProviderV2_0 = new SpeedManagerAlgorithmProviderV2((SpeedManagerAlgorithmProviderAdapter) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
