/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.softwarecatalog.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.softwarecatalog.service.http.SCLicenseServiceHttp;
import org.junit.BeforeClass;

public class SCLicenseServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SCLicenseServiceHttp sCLicenseServiceHttp0 = new SCLicenseServiceHttp();
      assertNotNull(sCLicenseServiceHttp0);
  }
}
