/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.swing.preferences.table;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.swing.preferences.table.ConditionTableColumnModel;
import org.junit.BeforeClass;

public class ConditionTableColumnModelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ConditionTableColumnModel conditionTableColumnModel0 = new ConditionTableColumnModel();
      assertEquals(4, conditionTableColumnModel0.getColumnCount());
  }
}
