/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.expanders;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.expanders.UDTTypeExpander;
import org.junit.BeforeClass;

public class UDTTypeExpanderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UDTTypeExpander uDTTypeExpander0 = new UDTTypeExpander();
      assertNotNull(uDTTypeExpander0);
  }
}
