/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.servlet;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.servlet.SetPortletClassLoaderServlet;
import org.junit.BeforeClass;

public class SetPortletClassLoaderServletEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SetPortletClassLoaderServlet setPortletClassLoaderServlet0 = new SetPortletClassLoaderServlet();
  }
}
