/*
 * This file was automatically generated by EvoSuite
 */

package org.heal.servlet;

import org.junit.Test;
import static org.junit.Assert.*;
import org.heal.servlet.DownloadAction;
import org.junit.BeforeClass;

public class DownloadActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DownloadAction downloadAction0 = new DownloadAction();
      boolean boolean0 = downloadAction0.actionRequiresLogin();
      assertEquals(true, boolean0);
  }
}
