/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web.filter.authz;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import org.jsecurity.web.filter.authz.PermissionsAuthorizationFilter;
import org.junit.BeforeClass;

public class PermissionsAuthorizationFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PermissionsAuthorizationFilter permissionsAuthorizationFilter0 = new PermissionsAuthorizationFilter();
      boolean boolean0 = permissionsAuthorizationFilter0.onPreHandle((ServletRequest) null, (ServletResponse) null, (Object) null);
      assertEquals(true, boolean0);
  }
}
