/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.fw.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.squirrel_sql.fw.gui.RightLabel;
import org.junit.BeforeClass;

public class RightLabelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RightLabel rightLabel0 = new RightLabel((String) null);
  }
}
