/*
 * This file was automatically generated by EvoSuite
 */

package bierse;

import org.junit.Test;
import static org.junit.Assert.*;
import bierse.Bierse;
import org.junit.BeforeClass;

public class BierseEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Bierse bierse0 = new Bierse();
  }
}
