/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.flags.messaging;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.Company;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portlet.flags.messaging.FlagsRequestMessageListener;
import org.junit.BeforeClass;

public class FlagsRequestMessageListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FlagsRequestMessageListener flagsRequestMessageListener0 = new FlagsRequestMessageListener();
      try {
        flagsRequestMessageListener0.notify((Company) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (-527L), (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (ServiceContext) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
