/*
 * This file was automatically generated by EvoSuite
 */

package com.isnetworks.ssh;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class LocalFileBrowserEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
