/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain001.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain001.simpletype.ChequeDelivery1Code;

public class ChequeDelivery1CodeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChequeDelivery1Code chequeDelivery1Code0 = new ChequeDelivery1Code();
      chequeDelivery1Code0.equals((Object) null);
  }
}
