/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain001.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain001.simpletype.GroupingIndicator;

public class GroupingIndicatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GroupingIndicator groupingIndicator0 = new GroupingIndicator();
      groupingIndicator0.equals((Object) null);
  }
}
