/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain001.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain001.simpletype.Instruction1Code;

public class Instruction1CodeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Instruction1Code instruction1Code0 = new Instruction1Code();
      instruction1Code0.equals((Object) null);
  }
}
