/*
 * This file was automatically generated by EvoSuite
 */

package Newzgrabber;

import org.junit.Test;
import static org.junit.Assert.*;
import Newzgrabber.IniUtility;
import java.util.Vector;
import org.junit.BeforeClass;

public class IniUtilityEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Vector<Object> vector0 = IniUtility.getProperties("");
      assertNull(vector0);
  }

  @Test
  public void test1()  throws Throwable  {
      IniUtility iniUtility0 = new IniUtility();
      assertNotNull(iniUtility0);
  }
}
