/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util.bridges.jsf.icefaces;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.bridges.jsf.icefaces.FileUploadManagedBean;
import org.junit.BeforeClass;

public class FileUploadManagedBeanEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FileUploadManagedBean fileUploadManagedBean0 = null;
      try {
        fileUploadManagedBean0 = new FileUploadManagedBean();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.icesoft.faces.webapp.xmlhttp.PersistentFacesState
         */
      }
  }
}
