/*
 * This file was automatically generated by EvoSuite
 */

package mygrid;

import org.junit.Test;
import static org.junit.Assert.*;
import mygrid.InvokeEngine;
import org.junit.BeforeClass;

public class InvokeEngineEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InvokeEngine invokeEngine0 = new InvokeEngine();
  }
}
