/*
 * This file was automatically generated by EvoSuite
 */

package it.pdfsam.console.tools.pdf;

import org.junit.Test;
import static org.junit.Assert.*;
import it.pdfsam.console.MainConsole;
import it.pdfsam.console.tools.pdf.PdfSplit;
import java.io.File;
import org.junit.BeforeClass;

public class PdfSplitEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MainConsole mainConsole0 = new MainConsole();
      PdfSplit pdfSplit0 = new PdfSplit((File) null, (File) null, (String) null, (String) null, (String) null, false, mainConsole0);
      assertEquals("", pdfSplit0.getOutMessage());
  }

  @Test
  public void test1()  throws Throwable  {
      MainConsole mainConsole0 = new MainConsole();
      PdfSplit pdfSplit0 = new PdfSplit((File) null, (File) null, "~c{j $!i$Qi", "~c{j $!i$Qi", "~c{j $!i$Qi", mainConsole0);
      assertEquals("", pdfSplit0.getOutHTMLMessage());
  }
}
