/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.shopping.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.shopping.model.impl.ShoppingCategoryImpl;
import org.junit.BeforeClass;

public class ShoppingCategoryImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShoppingCategoryImpl shoppingCategoryImpl0 = null;
      try {
        shoppingCategoryImpl0 = new ShoppingCategoryImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portlet.shopping.model.impl.ShoppingCategoryImpl
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ShoppingCategoryImpl shoppingCategoryImpl0 = null;
      try {
        shoppingCategoryImpl0 = new ShoppingCategoryImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portlet.shopping.model.impl.ShoppingCategoryImpl
         */
      }
  }
}
