/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.shopping.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.shopping.model.impl.ShoppingOrderImpl;
import org.evosuite.testcase.TestCaseExecutor;
import org.junit.BeforeClass;

public class ShoppingOrderImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShoppingOrderImpl shoppingOrderImpl0 = null;
      try {
        shoppingOrderImpl0 = new ShoppingOrderImpl();
        fail("Expecting exception: ExceptionInInitializerError");
      } catch(ExceptionInInitializerError e) {
      }
  }
}
