/*
 * This file was automatically generated by EvoSuite
 */

package org.firebirdsql.management;

import org.junit.Test;
import static org.junit.Assert.*;
import org.firebirdsql.management.FBCommandLine;
import org.junit.BeforeClass;

public class FBCommandLineEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FBCommandLine fBCommandLine0 = new FBCommandLine();
      assertNotNull(fBCommandLine0);
  }
}
