/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core.decision;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.card.BasicLand;
import lotus.core.card.Land;
import lotus.core.decision.PlayLand;
import org.junit.BeforeClass;

public class PlayLandEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BasicLand basicLand0 = new BasicLand();
      PlayLand playLand0 = new PlayLand((Land) basicLand0);
      // Undeclared exception!
      try {
        playLand0.applyDecision();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
