/*
 * This file was automatically generated by EvoSuite
 */

package glengineer.agents.settings;

import org.junit.Test;
import static org.junit.Assert.*;
import glengineer.agents.settings.Settings;
import org.junit.BeforeClass;

public class SettingsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Settings settings0 = new Settings();
  }
}
