/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.io;

import org.junit.Test;
import static org.junit.Assert.*;
import org.dom4j.io.PruningDispatchHandler;
import org.junit.BeforeClass;

public class PruningDispatchHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PruningDispatchHandler pruningDispatchHandler0 = new PruningDispatchHandler();
      assertNotNull(pruningDispatchHandler0);
  }
}
