/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.dao.shard.advice;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.dao.shard.advice.ShardAdvice;
import com.liferay.portal.dao.shard.advice.ShardPortletAdvice;
import org.junit.BeforeClass;

public class ShardPortletAdviceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShardPortletAdvice shardPortletAdvice0 = new ShardPortletAdvice();
      shardPortletAdvice0.setShardAdvice((ShardAdvice) null);
  }
}
