/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.jnfe.base.ModFrete;
import org.junit.BeforeClass;

public class ModFreteEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ModFrete modFrete0 = ModFrete.EMITENTE;
      char char0 = modFrete0.getValue();
      assertEquals('0', char0);
  }
}
