/*
 * This file was automatically generated by EvoSuite
 */

package uk.me.jockmacmad.jstate.state;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import uk.me.jockmacmad.jstate.state.StringMatchesGuardCondition;

public class StringMatchesGuardConditionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      StringMatchesGuardCondition stringMatchesGuardCondition0 = new StringMatchesGuardCondition((String) null);
      String string0 = stringMatchesGuardCondition0.toString();
      assertNotNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      StringMatchesGuardCondition stringMatchesGuardCondition0 = new StringMatchesGuardCondition((String) null);
      String string0 = stringMatchesGuardCondition0.getValue();
      assertNull(string0);
  }
}
