/*
 * This file was automatically generated by EvoSuite
 */

package de.paragon.explorer.event;

import org.junit.Test;
import static org.junit.Assert.*;
import de.paragon.explorer.event.ExplorerFrameEventConverter;
import de.paragon.explorer.figure.ExplorerFigure;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class ExplorerFrameEventConverterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ExplorerFigure explorerFigure0 = new ExplorerFigure();
      ExplorerFrameEventConverter explorerFrameEventConverter0 = null;
      try {
        explorerFrameEventConverter0 = new ExplorerFrameEventConverter(explorerFigure0);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
