/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.plugins.net.buddy.swt;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class BuddyPluginViewEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
