/*
 * This file was automatically generated by EvoSuite
 */

package com.gbshape.dbe.factory;

import org.junit.Test;
import static org.junit.Assert.*;
import com.gbshape.dbe.factory.DataBaseFactory;
import com.gbshape.dbe.idb.DataBase;
import org.junit.BeforeClass;

public class DataBaseFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test1()  throws Throwable  {
      DataBase dataBase0 = DataBaseFactory.getInstance("");
      assertNull(dataBase0);
  }

  @Test
  public void test2()  throws Throwable  {
      DataBase dataBase0 = DataBaseFactory.getInstance("error");
      assertNull(dataBase0);
  }
}
