/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw.updater;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.mfw.updater.UpdateRequest;
import org.junit.BeforeClass;

public class UpdateRequestEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpdateRequest updateRequest0 = new UpdateRequest();
  }
}
