/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.shopping.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.shopping.service.http.ShoppingCouponServiceHttp;
import org.junit.BeforeClass;

public class ShoppingCouponServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShoppingCouponServiceHttp shoppingCouponServiceHttp0 = new ShoppingCouponServiceHttp();
      assertNotNull(shoppingCouponServiceHttp0);
  }
}
