/*
 * This file was automatically generated by EvoSuite
 */

package logging;

import org.junit.Test;
import static org.junit.Assert.*;
import logging.Logging;
import org.junit.BeforeClass;

public class LoggingEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Logging.getInstance();
  }
}
