/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.fw.id;

import org.junit.Test;
import static org.junit.Assert.*;
import java.beans.PropertyDescriptor;
import net.sourceforge.squirrel_sql.fw.id.UidIdentifierBeanInfo;
import org.junit.BeforeClass;

public class UidIdentifierBeanInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UidIdentifierBeanInfo uidIdentifierBeanInfo0 = new UidIdentifierBeanInfo();
      PropertyDescriptor[] propertyDescriptorArray0 = uidIdentifierBeanInfo0.getPropertyDescriptors();
      assertNotNull(propertyDescriptorArray0);
  }
}
