/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.core.devices.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.core.devices.impl.DeviceManagerImpl;
import com.aelitis.azureus.core.devices.impl.DeviceiTunesManager;
import org.junit.BeforeClass;

public class DeviceiTunesManagerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DeviceiTunesManager deviceiTunesManager0 = new DeviceiTunesManager((DeviceManagerImpl) null);
      assertNotNull(deviceiTunesManager0);
  }
}
