/*
 * This file was automatically generated by EvoSuite
 */

package sound;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import sound.SoundTest;

public class SoundTestEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SoundTest soundTest0 = new SoundTest();
      assertNotNull(soundTest0);
  }
}
