/*
 * This file was automatically generated by EvoSuite
 */

package sound;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import sound.Sound;

public class SoundEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Sound sound0 = null;
      try {
        sound0 = new Sound();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class sound.Sound
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Sound sound0 = null;
      try {
        sound0 = new Sound("P&");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class sound.Sound
         */
      }
  }
}
