/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain004.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain004.simpletype.IBANIdentifier;

public class IBANIdentifierEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IBANIdentifier iBANIdentifier0 = new IBANIdentifier();
      iBANIdentifier0.equals((Object) null);
  }
}
