/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain004.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain004.simpletype.ISODate;

public class ISODateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ISODate iSODate0 = new ISODate();
      iSODate0.equals((Object) null);
  }
}
