/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain004.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain004.simpletype.ItalianDomesticIdentifier;

public class ItalianDomesticIdentifierEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ItalianDomesticIdentifier italianDomesticIdentifier0 = new ItalianDomesticIdentifier();
      italianDomesticIdentifier0.equals((Object) null);
  }
}
