/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain004.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain004.simpletype.Max35Text;

public class Max35TextEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Max35Text max35Text0 = new Max35Text();
      max35Text0.equals((Object) null);
  }
}
