/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.wiki.importers;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.wiki.importers.WikiImporterKeys;
import org.junit.BeforeClass;

public class WikiImporterKeysEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      WikiImporterKeys wikiImporterKeys0 = new WikiImporterKeys();
  }
}
