/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.probeframework.javaclient.api.probe;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.probeframework.javaclient.api.probe.ByteProbe;
import fi.vtt.probeframework.javaclient.api.probe.PFTest;
import fi.vtt.probeframework.javaclient.protocol.messages.Precision;
import org.junit.BeforeClass;

public class ByteProbeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PFTest test = new PFTest("p", "1.0", "sut", Precision.SECOND, "n", "s");
      ByteProbe byteProbe0 = new ByteProbe(test, (byte)26, "");
      byte[] byteArray0 = new byte[4];
      byteProbe0.data(byteArray0);
  }

  @Test
  public void test1()  throws Throwable  {
      PFTest test = new PFTest("p", "1.0", "sut", Precision.SECOND, "n", "s");
      ByteProbe byteProbe0 = new ByteProbe(test, (byte)0, "");
      assertNotNull(byteProbe0);
  }
}
