/*
 * This file was automatically generated by EvoSuite
 */

package org.json.simple.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.json.simple.parser.Yytoken;
import org.junit.BeforeClass;

public class YytokenEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Object object0 = new Object();
      Yytoken yytoken0 = new Yytoken(0, object0);
      String string0 = yytoken0.toString();
      assertEquals(0, yytoken0.type);
      assertNotNull(string0);
  }
}
