/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.expando.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.expando.model.ExpandoTableConstants;
import org.junit.BeforeClass;

public class ExpandoTableConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ExpandoTableConstants expandoTableConstants0 = new ExpandoTableConstants();
  }
}
