/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.plugin.rotate.GUI;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.plugin.rotate.GUI.RotateMainGUI;

public class RotateMainGUIEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RotateMainGUI rotateMainGUI0 = null;
      try {
        rotateMainGUI0 = new RotateMainGUI();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
