/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.testgen.model.invariants;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.testgen.model.invariants.StringAttribute;
import org.junit.BeforeClass;

public class StringAttributeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      StringAttribute stringAttribute0 = new StringAttribute("", "");
      String string0 = stringAttribute0.getValue();
      assertEquals("", string0);
  }
}
