/*
 * This file was automatically generated by EvoSuite
 */

package src;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import src.XMLable;

public class XMLableEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XMLable xMLable0 = new XMLable();
  }
}
