/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.BankAcctFeatLimit;

public class BankAcctFeatLimitEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BankAcctFeatLimit bankAcctFeatLimit0 = new BankAcctFeatLimit();
      bankAcctFeatLimit0.equals((Object) null);
  }
}
