/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.BankSvcChkSumAudRq;

public class BankSvcChkSumAudRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BankSvcChkSumAudRq bankSvcChkSumAudRq0 = new BankSvcChkSumAudRq();
      bankSvcChkSumAudRq0.equals((Object) "org.sourceforge.ifx.framework.element.BankSvcChkSumAudRq = {\n  Method = NULL\n  RqUID = NULL\n  MsgRqHdr = NULL\n  AsyncRqUID = NULL\n  CustId = NULL\n  RecCtrlIn = NULL\n  SelRangeDt = NULL\n  BankSvcChkSumId = NULL\n}");
  }
}
