/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.BankSvcChkSumSyncRq;

public class BankSvcChkSumSyncRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BankSvcChkSumSyncRq bankSvcChkSumSyncRq0 = new BankSvcChkSumSyncRq();
      bankSvcChkSumSyncRq0.equals((Object) "org.sourceforge.ifx.framework.element.AppEffDt = {\n  String = Exception! java.lang.ClassCastException: java.lang.String cannot be cast to org.sourceforge.ifx.basetypes.IFXObject\n}");
  }
}
