/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.BankSvcChkSumRec;

public class BankSvcChkSumRecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BankSvcChkSumRec bankSvcChkSumRec0 = new BankSvcChkSumRec();
      bankSvcChkSumRec0.equals((Object) "org.sourceforge.ifx.framework.element.RefType = {\n  String = NULL\n}");
  }
}
