/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CardPrefWithdrawal;

public class CardPrefWithdrawalEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CardPrefWithdrawal cardPrefWithdrawal0 = new CardPrefWithdrawal();
      cardPrefWithdrawal0.equals((Object) "org.sourceforge.ifx.framework.element.Country = {\n  String = NULL\n}");
  }
}
