/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CardPrefModRs;

public class CardPrefModRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CardPrefModRs cardPrefModRs0 = new CardPrefModRs();
      cardPrefModRs0.equals((Object) "org.sourceforge.ifx.framework.element.CardPref = {\n  CardPrefMisc = NULL\n  CardPrefWithdrawal = NULL\n  CardPrefDeposit = NULL\n}");
  }
}
