/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CashSignature;

public class CashSignatureEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CashSignature cashSignature0 = new CashSignature();
      cashSignature0.equals((Object) "org.sourceforge.ifx.framework.element.ContentType = {\n  String = NULL\n}");
  }
}
