/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.ChkIssueAudRs;

public class ChkIssueAudRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChkIssueAudRs chkIssueAudRs0 = new ChkIssueAudRs();
      Object object0 = new Object();
      chkIssueAudRs0.equals(object0);
  }
}
