/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.ChkOrdMsgRec;

public class ChkOrdMsgRecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChkOrdMsgRec chkOrdMsgRec0 = new ChkOrdMsgRec();
      chkOrdMsgRec0.equals((Object) "org.sourceforge.ifx.framework.element.TrnSeqCntr = {\n  String = NULL\n}");
  }
}
