/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.ChkOrdInqRs;

public class ChkOrdInqRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChkOrdInqRs chkOrdInqRs0 = new ChkOrdInqRs();
      chkOrdInqRs0.equals((Object) "org.sourceforge.ifx.framework.element.POSAgent = {\n  AgentType = NULL\n  AgentId = NULL\n}");
  }
}
