/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.ChksumRec;

public class ChksumRecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChksumRec chksumRec0 = new ChksumRec();
      chksumRec0.equals((Object) "org.sourceforge.ifx.framework.element.RefType = {\n  String = NULL\n}");
  }
}
