/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.ChksumAudRs;

public class ChksumAudRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChksumAudRs chksumAudRs0 = new ChksumAudRs();
      chksumAudRs0.equals((Object) "org.sourceforge.ifx.framework.element.BinLength = {\n  String = Exception! java.lang.reflect.InvocationTargetException\n}");
  }
}
