/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CompRemitStmtInqRq;

public class CompRemitStmtInqRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompRemitStmtInqRq compRemitStmtInqRq0 = new CompRemitStmtInqRq();
      compRemitStmtInqRq0.equals((Object) "org.sourceforge.ifx.framework.element.RefId = {\n  String = NULL\n}");
  }
}
