/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CompRemitStmtAddRs;

public class CompRemitStmtAddRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompRemitStmtAddRs compRemitStmtAddRs0 = new CompRemitStmtAddRs();
      compRemitStmtAddRs0.equals((Object) null);
  }
}
