/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CreditAuthAdviseRs;

public class CreditAuthAdviseRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CreditAuthAdviseRs creditAuthAdviseRs0 = new CreditAuthAdviseRs();
      creditAuthAdviseRs0.equals((Object) null);
  }
}
