/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CreditAuthAdviseRq;

public class CreditAuthAdviseRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CreditAuthAdviseRq creditAuthAdviseRq0 = new CreditAuthAdviseRq();
      creditAuthAdviseRq0.equals((Object) "org.sourceforge.ifx.framework.element.Addr3 = {\n  String = NULL\n}");
  }
}
