/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CreditInfo;

public class CreditInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CreditInfo creditInfo0 = new CreditInfo();
      creditInfo0.equals((Object) "org.sourceforge.ifx.framework.element.NameSuffix = {\n  String = NULL\n}");
  }
}
