/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CreditAuthAudRq;

public class CreditAuthAudRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CreditAuthAudRq creditAuthAudRq0 = new CreditAuthAudRq();
      creditAuthAudRq0.equals((Object) "org.sourceforge.ifx.framework.element.CreditAuthAudRq = {\n  Method = NULL\n  RqUID = NULL\n  MsgRqHdr = NULL\n  AsyncRqUID = NULL\n  CustId = NULL\n  RecCtrlIn = NULL\n  SelRangeDt = NULL\n  CreditAuthId = NULL\n}");
  }
}
