/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustPayeeTypeModRq;

public class CustPayeeTypeModRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustPayeeTypeModRq custPayeeTypeModRq0 = new CustPayeeTypeModRq();
      custPayeeTypeModRq0.equals((Object) null);
  }
}
