/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustPayeeTypeModRs;

public class CustPayeeTypeModRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustPayeeTypeModRs custPayeeTypeModRs0 = new CustPayeeTypeModRs();
      custPayeeTypeModRs0.equals((Object) "org.sourceforge.ifx.framework.element.StateProv = {\n  String = NULL\n}");
  }
}
