/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustIdInqRs;

public class CustIdInqRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustIdInqRs custIdInqRs0 = new CustIdInqRs();
      custIdInqRs0.equals((Object) "org.sourceforge.ifx.framework.element.AsyncRsInfo = {\n  ExpDt = NULL\n  AvailDt = NULL\n}");
  }
}
