/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustDiscStatusModRs;

public class CustDiscStatusModRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustDiscStatusModRs custDiscStatusModRs0 = new CustDiscStatusModRs();
      custDiscStatusModRs0.equals((Object) "org.sourceforge.ifx.framework.element.StateProv = {\n  String = NULL\n}");
  }
}
