/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustDiscInqRs;

public class CustDiscInqRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustDiscInqRs custDiscInqRs0 = new CustDiscInqRs();
      custDiscInqRs0.equals((Object) "org.sourceforge.ifx.framework.element.Name = {\n  String = NULL\n}");
  }
}
