/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustSvcSyncRs;

public class CustSvcSyncRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustSvcSyncRs custSvcSyncRs0 = new CustSvcSyncRs();
      custSvcSyncRs0.equals((Object) "org.sourceforge.ifx.framework.element.PSSCATSecLevel = {\n  String = NULL\n}");
  }
}
