/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.CustMsgRec;

public class CustMsgRecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CustMsgRec custMsgRec0 = new CustMsgRec();
      custMsgRec0.equals((Object) "org.sourceforge.ifx.framework.element.Nickname = {\n  String = NULL\n}");
  }
}
