/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DebitRevRs;

public class DebitRevRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DebitRevRs debitRevRs0 = new DebitRevRs();
      debitRevRs0.equals((Object) "org.sourceforge.ifx.framework.element.TrnRqUID = {\n  String = NULL\n}");
  }
}
