/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DepAcctStmtMsgRqInfo;

public class DepAcctStmtMsgRqInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DepAcctStmtMsgRqInfo depAcctStmtMsgRqInfo0 = new DepAcctStmtMsgRqInfo();
      depAcctStmtMsgRqInfo0.equals((Object) null);
  }
}
