/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DepBkOrdInfo;

public class DepBkOrdInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DepBkOrdInfo depBkOrdInfo0 = new DepBkOrdInfo();
      depBkOrdInfo0.equals((Object) "org.sourceforge.ifx.framework.element.IdentType = {\n  String = NULL\n}");
  }
}
