/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DepBkOrdRevRs;

public class DepBkOrdRevRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DepBkOrdRevRs depBkOrdRevRs0 = new DepBkOrdRevRs();
      depBkOrdRevRs0.equals((Object) null);
  }
}
