/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DevCdmBinMaxCount;

public class DevCdmBinMaxCountEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DevCdmBinMaxCount devCdmBinMaxCount0 = new DevCdmBinMaxCount();
      Object object0 = new Object();
      devCdmBinMaxCount0.equals(object0);
  }
}
