/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DevDetailTtu;

public class DevDetailTtuEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DevDetailTtu devDetailTtu0 = new DevDetailTtu();
      devDetailTtu0.equals((Object) "org.sourceforge.ifx.framework.element.DevDetailTtu = {\n  DevTtuType = NULL\n  DevTtuOperation = NULL\n  DevTtuKbd = NULL\n  DevTtuKbdLock = NULL\n  DevTtuLed = NULL\n}");
  }
}
