/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.DevSiuEnhancedAudio;

public class DevSiuEnhancedAudioEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DevSiuEnhancedAudio devSiuEnhancedAudio0 = new DevSiuEnhancedAudio();
      devSiuEnhancedAudio0.equals((Object) null);
  }
}
