/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.ForExDealSyncRq;

public class ForExDealSyncRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ForExDealSyncRq forExDealSyncRq0 = new ForExDealSyncRq();
      forExDealSyncRq0.equals((Object) "org.sourceforge.ifx.framework.element.ForExDealId = {\n  String = NULL\n}");
  }
}
