/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.MediaAcctAdjAddRs;

public class MediaAcctAdjAddRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MediaAcctAdjAddRs mediaAcctAdjAddRs0 = new MediaAcctAdjAddRs();
      mediaAcctAdjAddRs0.equals((Object) null);
  }
}
