/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PassbkMsgRec;

public class PassbkMsgRecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PassbkMsgRec passbkMsgRec0 = new PassbkMsgRec();
      passbkMsgRec0.equals((Object) "org.sourceforge.ifx.framework.element.Token = {\n  String = NULL\n}");
  }
}
