/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PassbkLastBalPrinted;

public class PassbkLastBalPrintedEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PassbkLastBalPrinted passbkLastBalPrinted0 = new PassbkLastBalPrinted();
      passbkLastBalPrinted0.equals((Object) null);
  }
}
