/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PaySupt;

public class PaySuptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PaySupt paySupt0 = new PaySupt();
      paySupt0.equals((Object) "org.sourceforge.ifx.framework.element.CurCode = {\n  String = NULL\n}");
  }
}
