/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PaySvcRq;

public class PaySvcRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PaySvcRq paySvcRq0 = new PaySvcRq();
      paySvcRq0.equals((Object) "org.sourceforge.ifx.framework.pain004.simpletype.CurrencyCode = {\n  String = NULL\n}");
  }
}
