/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PmtEnclAudRq;

public class PmtEnclAudRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PmtEnclAudRq pmtEnclAudRq0 = new PmtEnclAudRq();
      pmtEnclAudRq0.equals((Object) "org.sourceforge.ifx.framework.element.AmtX = {\n  CurCode = NULL\n  Amt = NULL\n  CurRate = NULL\n  CurConvertRule = NULL\n}");
  }
}
