/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PmtRevRq;

public class PmtRevRqEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PmtRevRq pmtRevRq0 = new PmtRevRq();
      pmtRevRq0.equals((Object) "org.sourceforge.ifx.framework.element.PmtInstType = {\n  String = NULL\n}");
  }
}
