/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.PostingSessionMsgRec;

public class PostingSessionMsgRecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PostingSessionMsgRec postingSessionMsgRec0 = new PostingSessionMsgRec();
      postingSessionMsgRec0.equals((Object) null);
  }
}
