/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.RecXferRevRs;

public class RecXferRevRsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RecXferRevRs recXferRevRs0 = new RecXferRevRs();
      recXferRevRs0.equals((Object) "org.sourceforge.ifx.framework.element.OriginatorType = {\n  String = Exception! java.lang.reflect.InvocationTargetException\n}");
  }
}
