/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.SelRangePrcDt;

public class SelRangePrcDtEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SelRangePrcDt selRangePrcDt0 = new SelRangePrcDt();
      selRangePrcDt0.equals((Object) "_d[z|OU]4{vO,");
  }
}
