/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.TerminalSPObjInfo;

public class TerminalSPObjInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TerminalSPObjInfo terminalSPObjInfo0 = new TerminalSPObjInfo();
      terminalSPObjInfo0.equals((Object) "_d[z|OU]4{vO,");
  }
}
