/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.element.XferStatus;

public class XferStatusEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XferStatus xferStatus0 = new XferStatus();
      xferStatus0.equals((Object) "org.sourceforge.ifx.framework.element.Status = {\n  Id = NULL\n  StatusDesc = NULL\n  StatusCode = NULL\n  ServerStatusCode = NULL\n  Severity = NULL\n  AdditionalStatus = NULL\n  AsyncRsInfo = NULL\n}");
  }
}
