/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.business;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.business.ApplicationCloser;
import org.pdfsam.guiclient.gui.frames.JMainFrame;

public class ApplicationCloserEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ApplicationCloser applicationCloser0 = new ApplicationCloser((JMainFrame) null);
      assertNotNull(applicationCloser0);
  }
}
