/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.business;

import org.junit.Test;
import static org.junit.Assert.*;

public class ClosableTabbedPanelAdderEvoSuiteTest {

}
