/*
 * This file was automatically generated by EvoSuite
 */

package osa.ora.server;

import org.junit.Test;
import static org.junit.Assert.*;
import java.rmi.RemoteException;
import org.junit.BeforeClass;
import osa.ora.server.StopServer;

public class StopServerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      StopServer stopServer0 = null;
      try {
        stopServer0 = new StopServer();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
