/*
 * This file was automatically generated by EvoSuite
 */

package freemind.common;

import org.junit.Test;
import static org.junit.Assert.*;
import freemind.common.DontShowNotificationProperty;
import org.junit.BeforeClass;

public class DontShowNotificationPropertyEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DontShowNotificationProperty dontShowNotificationProperty0 = new DontShowNotificationProperty("", "");
      assertEquals("", dontShowNotificationProperty0.getLabel());
  }
}
