/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.plugin.docinfo.GUI;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.plugin.docinfo.GUI.DocInfoMainGUI;
import org.pdfsam.plugin.docinfo.GUI.SetMetaFieldsHook;

public class SetMetaFieldsHookEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SetMetaFieldsHook setMetaFieldsHook0 = new SetMetaFieldsHook((DocInfoMainGUI) null);
      assertNotNull(setMetaFieldsHook0);
  }
}
