/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.common.util;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.statsbiblioteket.summa.common.util.ConfigurationTranscoder;
import org.junit.BeforeClass;

public class ConfigurationTranscoderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ConfigurationTranscoder configurationTranscoder0 = new ConfigurationTranscoder();
  }
}
