/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.messageboards.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portlet.messageboards.model.impl.MBMailingListImpl;
import org.junit.BeforeClass;

public class MBMailingListBaseImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MBMailingListImpl mBMailingListImpl0 = null;
      try {
        mBMailingListImpl0 = new MBMailingListImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portlet.messageboards.model.impl.MBMailingListImpl
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      MBMailingListImpl mBMailingListImpl0 = null;
      try {
        mBMailingListImpl0 = new MBMailingListImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portlet.messageboards.model.impl.MBMailingListImpl
         */
      }
  }
}
