/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.dynamicdatalists.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.dynamicdatalists.util.FreeMarkerTemplateParser;
import org.junit.BeforeClass;

public class FreeMarkerTemplateParserEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FreeMarkerTemplateParser freeMarkerTemplateParser0 = new FreeMarkerTemplateParser();
      // Undeclared exception!
      try {
        freeMarkerTemplateParser0.getErrorTemplateId();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.util.PropsValues
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      FreeMarkerTemplateParser freeMarkerTemplateParser0 = new FreeMarkerTemplateParser();
      // Undeclared exception!
      try {
        freeMarkerTemplateParser0.getTemplateContext();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * com/liferay/portal/kernel/template/StringTemplateResource
         */
      }
  }
}
