/*
 * This file was automatically generated by EvoSuite
 */

package org.jcvi.jillion.assembly;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jcvi.jillion.assembly.DefaultScaffoldDataStore;
import org.junit.BeforeClass;

public class DefaultScaffoldDataStoreEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultScaffoldDataStore.createBuilder();
  }
}
