/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core.phases;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.phases.CombatBeginningPhase;
import org.junit.BeforeClass;

public class CombatBeginningPhaseEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CombatBeginningPhase combatBeginningPhase0 = new CombatBeginningPhase();
      // Undeclared exception!
      try {
        combatBeginningPhase0.doPhase();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
