/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core.phases;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.phases.EndOfTurnPhase;
import org.junit.BeforeClass;

public class EndOfTurnPhaseEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      EndOfTurnPhase endOfTurnPhase0 = new EndOfTurnPhase();
      endOfTurnPhase0.doPhase();
  }
}
