/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core.phases;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.phases.UntapPhase;
import org.junit.BeforeClass;

public class UntapPhaseEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UntapPhase untapPhase0 = new UntapPhase();
      assertNotNull(untapPhase0);
  }
}
