/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.apache.bridges.struts;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class LiferayStrutsRequestImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
