/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_2;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_0_2.UpgradeExpando;
import org.junit.BeforeClass;

public class UpgradeExpandoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeExpando upgradeExpando0 = new UpgradeExpando();
      try {
        upgradeExpando0.doUpgrade();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      UpgradeExpando upgradeExpando0 = new UpgradeExpando();
      try {
        upgradeExpando0.addValue(1171L, 1171L, 1171L, 1171L, 1171L, 1171L, 1171L, "");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      UpgradeExpando upgradeExpando0 = new UpgradeExpando();
      try {
        upgradeExpando0.addRow(1596L, 1596L, 1596L, 1596L);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
