/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.ui.swt.shells.main;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.ui.swt.shells.main.MainWindowFactory;
import org.junit.BeforeClass;

public class MainWindowFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MainWindowFactory mainWindowFactory0 = new MainWindowFactory();
      assertNotNull(mainWindowFactory0);
  }
}
