/*
 * This file was automatically generated by EvoSuite
 */

package corina.util;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.util.ColorPair;
import java.awt.Color;
import org.junit.BeforeClass;

public class ColorPairEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Color color0 = Color.DARK_GRAY;
      ColorPair colorPair0 = new ColorPair("#", color0);
      assertNotNull(colorPair0);
  }
}
