/*
 * This file was automatically generated by EvoSuite
 */

package corina.util;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.util.PropertiesWindow;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class PropertiesWindowEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        PropertiesWindow.showPropertiesWindow();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
