/*
 * This file was automatically generated by EvoSuite
 */

package com.browsersoft.aacs;

import org.junit.Test;
import static org.junit.Assert.*;
import com.browsersoft.aacs.LoginFilter;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import org.junit.BeforeClass;

public class LoginFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoginFilter loginFilter0 = new LoginFilter();
      loginFilter0.init((FilterConfig) null);
  }

  @Test
  public void test1()  throws Throwable  {
      LoginFilter loginFilter0 = new LoginFilter();
      loginFilter0.destroy();
  }
}
