/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.messageboards.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.messageboards.service.http.MBMessageServiceHttp;
import org.junit.BeforeClass;

public class MBMessageServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MBMessageServiceHttp mBMessageServiceHttp0 = new MBMessageServiceHttp();
      assertNotNull(mBMessageServiceHttp0);
  }
}
