/*
 * This file was automatically generated by EvoSuite
 */

package fr.unice.gfarce.main;

import org.junit.Test;
import static org.junit.Assert.*;
import fr.unice.gfarce.dao.DaoFactoryException;
import fr.unice.gfarce.main.Controler;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class ControlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Controler controler0 = null;
      try {
        controler0 = new Controler();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
