/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.server.ui.wizard;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class SapNWRuntimeCompositeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
