/*
 * This file was automatically generated by EvoSuite
 */

package de.paragon.explorer.model;

import org.junit.Test;
import static org.junit.Assert.*;
import de.paragon.explorer.model.AttributeModel;
import org.junit.BeforeClass;

public class ObjectModelPartEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AttributeModel attributeModel0 = new AttributeModel();
  }
}
