/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web.filter.authc;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jsecurity.web.filter.authc.PassThruAuthenticationFilter;
import org.junit.BeforeClass;

public class PassThruAuthenticationFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PassThruAuthenticationFilter passThruAuthenticationFilter0 = new PassThruAuthenticationFilter();
      assertNotNull(passThruAuthenticationFilter0);
  }
}
