/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web.filter.authc;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import org.jsecurity.web.filter.authc.UserFilter;
import org.junit.BeforeClass;

public class UserFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UserFilter userFilter0 = new UserFilter();
      try {
        userFilter0.onAccessDenied((ServletRequest) null, (ServletResponse) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
