/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.workflow;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.workflow.MyWorkflowInstancesControlPanelEntry;
import org.junit.BeforeClass;

public class MyWorkflowInstancesControlPanelEntryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MyWorkflowInstancesControlPanelEntry myWorkflowInstancesControlPanelEntry0 = new MyWorkflowInstancesControlPanelEntry();
      assertNotNull(myWorkflowInstancesControlPanelEntry0);
  }
}
