/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.workflow;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.workflow.WorkflowLinkAdvice;
import org.junit.BeforeClass;

public class WorkflowLinkAdviceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      WorkflowLinkAdvice workflowLinkAdvice0 = new WorkflowLinkAdvice();
      assertNotNull(workflowLinkAdvice0);
  }
}
