/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.sharepoint.methods;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.sharepoint.ResponseElement;
import com.liferay.portal.sharepoint.SharepointRequest;
import com.liferay.portal.sharepoint.methods.OpenServiceMethodImpl;
import java.util.List;
import org.junit.BeforeClass;

public class OpenServiceMethodImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenServiceMethodImpl openServiceMethodImpl0 = new OpenServiceMethodImpl();
      SharepointRequest sharepointRequest0 = new SharepointRequest("open service");
      List<ResponseElement> list0 = openServiceMethodImpl0.getElements(sharepointRequest0);
      assertEquals(false, list0.isEmpty());
  }

  @Test
  public void test1()  throws Throwable  {
      OpenServiceMethodImpl openServiceMethodImpl0 = new OpenServiceMethodImpl();
      String string0 = openServiceMethodImpl0.getMethodName();
      assertEquals("open service", string0);
  }
}
