/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import org.junit.BeforeClass;

public class PersistedModelLocalServiceRegistryUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        PersistedModelLocalServiceRegistryUtil.getPersistedModelLocalService("%u9");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        PersistedModelLocalServiceRegistryUtil.isPermissionedModelLocalService("`");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
