/*
 * This file was automatically generated by EvoSuite
 */

package org.gudy.azureus2.ui.swt.shells;

import org.junit.Test;
import static org.junit.Assert.*;
import org.gudy.azureus2.ui.swt.shells.ShellFader;
import org.junit.BeforeClass;

public class ShellFaderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShellFader shellFader0 = new ShellFader();
  }
}
