/*
 * This file was automatically generated by EvoSuite
 */

package simulator.WSA;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import simulator.WSA.WaterSupplierAgent;

public class WaterSupplierAgentEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      WaterSupplierAgent waterSupplierAgent0 = new WaterSupplierAgent();
      // Undeclared exception!
      try {
        waterSupplierAgent0.setup();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
