/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.util.NullWrapper;
import org.junit.BeforeClass;

public class NullWrapperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      NullWrapper nullWrapper0 = new NullWrapper("v");
      String string0 = nullWrapper0.getClassName();
      assertEquals("v", string0);
  }
}
