/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.util.RandomAccessInputStream;
import java.io.IOException;
import java.io.InputStream;
import org.junit.BeforeClass;

public class RandomAccessInputStreamEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RandomAccessInputStream randomAccessInputStream0 = null;
      try {
        randomAccessInputStream0 = new RandomAccessInputStream((InputStream) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
