/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw.bundle.server.plugins.webui.availabilitypage;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.mfw.bundle.server.plugins.webui.availabilitypage.DetachableDeviceModel;
import fi.vtt.noen.mfw.bundle.server.plugins.webui.availabilitypage.DeviceDesc;
import org.junit.BeforeClass;

public class DetachableDeviceModelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DetachableDeviceModel detachableDeviceModel0 = null;
      try {
        detachableDeviceModel0 = new DetachableDeviceModel((DeviceDesc) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class fi.vtt.noen.mfw.bundle.server.plugins.webui.availabilitypage.DetachableDeviceModel
         */
      }
  }
}
