/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class BurnEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Burn burn0 = new Burn();
      assertNotNull(burn0);
  }

  @Test
  public void test1()  throws Throwable  {
      Burn burn0 = new Burn(true);
      assertNotNull(burn0);
  }
}
