/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class CaptureEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Capture capture0 = new Capture();
      // Undeclared exception!
      try {
        capture0.run();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Capture capture0 = new Capture(122, 122, (GUI) null);
      assertNotNull(capture0);
  }
}
