/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.events;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.events.ClearRenderParametersAction;
import org.junit.BeforeClass;

public class ClearRenderParametersActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ClearRenderParametersAction clearRenderParametersAction0 = new ClearRenderParametersAction();
      assertNotNull(clearRenderParametersAction0);
  }
}
