/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.events;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.events.LogSessionIdAction;
import org.junit.BeforeClass;

public class LogSessionIdActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LogSessionIdAction logSessionIdAction0 = new LogSessionIdAction();
      assertNotNull(logSessionIdAction0);
  }
}
