/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.http.ImageServiceSoap;
import java.rmi.RemoteException;
import org.junit.BeforeClass;

public class ImageServiceSoapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      try {
        ImageServiceSoap.getImage(822L);
        fail("Expecting exception: RemoteException");
      } catch(RemoteException e) {
        /*
         * BeanLocator has not been set
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ImageServiceSoap imageServiceSoap0 = new ImageServiceSoap();
      assertNotNull(imageServiceSoap0);
  }
}
