/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.http.LayoutSetBranchServiceHttp;
import org.junit.BeforeClass;

public class LayoutSetBranchServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutSetBranchServiceHttp layoutSetBranchServiceHttp0 = new LayoutSetBranchServiceHttp();
      assertNotNull(layoutSetBranchServiceHttp0);
  }
}
