/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.http.PluginSettingServiceSoap;
import java.rmi.RemoteException;
import org.junit.BeforeClass;

public class PluginSettingServiceSoapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      try {
        PluginSettingServiceSoap.updatePluginSetting((-1L), "<?@NO^?N^<<)90UU", "", "", false);
        fail("Expecting exception: RemoteException");
      } catch(RemoteException e) {
        /*
         * BeanLocator has not been set
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      PluginSettingServiceSoap pluginSettingServiceSoap0 = new PluginSettingServiceSoap();
      assertNotNull(pluginSettingServiceSoap0);
  }
}
