/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.http.RepositoryServiceHttp;
import org.junit.BeforeClass;

public class RepositoryServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RepositoryServiceHttp repositoryServiceHttp0 = new RepositoryServiceHttp();
      assertNotNull(repositoryServiceHttp0);
  }
}
