/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.freemarker;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.freemarker.LiferayObjectWrapper;
import freemarker.template.TemplateModelException;
import org.junit.BeforeClass;

public class LiferayObjectWrapperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LiferayObjectWrapper liferayObjectWrapper0 = null;
      try {
        liferayObjectWrapper0 = new LiferayObjectWrapper();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.freemarker.LiferayObjectWrapper
         */
      }
  }
}
