/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.testgen.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.testgen.parser.InterfaceParser;
import java.util.Collection;
import java.util.LinkedList;
import org.evosuite.testcase.CodeUnderTestException;
import org.junit.BeforeClass;

public class InterfaceParserEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = InterfaceParser.class;
      Class<?> class1 = InterfaceParser.class;
      InterfaceParser.methodNames(class1);
      InterfaceParser.methodNames(class0);
      InterfaceParser interfaceParser0 = new InterfaceParser();
      Class<?> class2 = InterfaceParser.class;
      LinkedList<Class<Object>> linkedList0 = new LinkedList<Class<Object>>();
  }
}
