/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.taglib.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.taglib.util.BodyBottomTag;
import org.junit.BeforeClass;

public class BodyBottomTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BodyBottomTag bodyBottomTag0 = new BodyBottomTag();
  }
}
