/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.plugin.mix.GUI;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.plugin.mix.GUI.MixMainGUI;

public class MixMainGUIEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MixMainGUI mixMainGUI0 = null;
      try {
        mixMainGUI0 = new MixMainGUI();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
