/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.security.pwd;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.security.pwd.PasswordPolicyToolkit;
import org.junit.BeforeClass;

public class PasswordPolicyToolkitEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PasswordPolicyToolkit passwordPolicyToolkit0 = null;
      try {
        passwordPolicyToolkit0 = new PasswordPolicyToolkit();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.util.PropsValues
         */
      }
  }
}
