/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.configuration.services.xml;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.configuration.services.xml.XmlGuiConfigurationService;

public class XmlGuiConfigurationServiceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XmlGuiConfigurationService xmlGuiConfigurationService0 = null;
      try {
        xmlGuiConfigurationService0 = new XmlGuiConfigurationService();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
