/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.gm.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import dsachat.gm.gui.GmFrame;
import dsachat.gm.gui.InternalGmChatFrame;
import org.junit.BeforeClass;

public class InternalGmChatFrameEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InternalGmChatFrame internalGmChatFrame0 = null;
      try {
        internalGmChatFrame0 = new InternalGmChatFrame((GmFrame) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
