/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.swing.TextDialog;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class TextDialogEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        TextDialog.showException("cWA%\"uh>tv", (Throwable) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
