/*
 * This file was automatically generated by EvoSuite
 */

package weka.gui.explorer;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import weka.classifiers.trees.LMT;
import weka.core.Capabilities;
import weka.gui.explorer.Explorer;

public class ExplorerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LMT lMT0 = new LMT();
      Capabilities capabilities0 = lMT0.getCapabilities();
      Explorer.CapabilitiesFilterChangeEvent explorer_CapabilitiesFilterChangeEvent0 = new Explorer.CapabilitiesFilterChangeEvent((Object) "ToolTipText", capabilities0);
      Capabilities capabilities1 = explorer_CapabilitiesFilterChangeEvent0.getFilter();
      assertSame(capabilities1, capabilities0);
  }
}
