/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.util.collection;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.util.collection.CollectionEvent;
import org.junit.BeforeClass;

public class CollectionEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CollectionEvent collectionEvent0 = new CollectionEvent();
  }
}
