/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.trash;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.trash.TrashEntryConstants;
import org.junit.BeforeClass;

public class TrashEntryConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TrashEntryConstants trashEntryConstants0 = new TrashEntryConstants();
  }
}
