/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.search.facet.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.search.SearchContext;
import com.liferay.portal.kernel.search.facet.util.BaseFacetValueValidator;
import org.junit.BeforeClass;

public class BaseFacetValueValidatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BaseFacetValueValidator baseFacetValueValidator0 = new BaseFacetValueValidator();
      SearchContext searchContext0 = new SearchContext();
      boolean boolean0 = baseFacetValueValidator0.check(searchContext0, "`$}Svdx(8lK<t|9emf");
      assertEquals(true, boolean0);
  }
}
