/*
 * This file was automatically generated by EvoSuite
 */

package de.paragon.explorer.util;

import org.junit.Test;
import static org.junit.Assert.*;
import de.paragon.explorer.model.ExplorerModel;
import de.paragon.explorer.util.ExplorerManager;
import org.junit.BeforeClass;

public class ExplorerManagerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ExplorerManager explorerManager0 = ExplorerManager.INSTANCE;
      ExplorerModel explorerModel0 = new ExplorerModel();
      // Undeclared exception!
      try {
        explorerManager0.addExplorerModel(explorerModel0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
