/*
 * This file was automatically generated by EvoSuite
 */

package wheel;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import wheel.AssetProcessor;

public class AssetProcessorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AssetProcessor assetProcessor0 = new AssetProcessor();
      String string0 = assetProcessor0.replaceUrls("", "", 278);
      assertEquals("", string0);
  }
}
