/*
 * This file was automatically generated by EvoSuite
 */

package lotus.core.stack;

import org.junit.Test;
import static org.junit.Assert.*;
import lotus.core.stack.Stack;
import org.junit.BeforeClass;

public class StackEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Stack stack0 = new Stack();
      assertEquals(true, stack0.empty());
  }
}
