/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw.bundle.server.plugins.webui.bmresultspage;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.mfw.bundle.server.plugins.webui.bmresultspage.BMResult;
import fi.vtt.noen.mfw.bundle.server.plugins.webui.bmresultspage.DetachableBMResultModel;
import org.junit.BeforeClass;

public class DetachableBMResultModelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DetachableBMResultModel detachableBMResultModel0 = null;
      try {
        detachableBMResultModel0 = new DetachableBMResultModel((BMResult) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class fi.vtt.noen.mfw.bundle.server.plugins.webui.bmresultspage.DetachableBMResultModel
         */
      }
  }
}
