/*
 * This file was automatically generated by EvoSuite
 */

package server;

import org.junit.Test;
import static org.junit.Assert.*;
import client.BomberClient;
import org.junit.BeforeClass;
import server.ClientInfo;

public class ClientInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        BomberClient.getInstance();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class client.BomberClient
         */
      }
  }
}
