/*
 * This file was automatically generated by EvoSuite
 */

package server;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Vector;
import org.junit.BeforeClass;
import server.ClientInfo;
import server.ServerGameRound;
import server.ServerGameSession;

public class ServerGameRoundEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Vector<ClientInfo> vector0 = new Vector<ClientInfo>();
      ServerGameRound serverGameRound0 = null;
      try {
        serverGameRound0 = new ServerGameRound((ServerGameSession) null, vector0, "\"");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class server.ServerGameRound
         */
      }
  }
}
