/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.ChkOrdStatusCode_Type;

public class ChkOrdStatusCode_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ChkOrdStatusCode_Type chkOrdStatusCode_Type0 = new ChkOrdStatusCode_Type();
      chkOrdStatusCode_Type0.equals((Object) null);
  }
}
