/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.CompRemitStmtId_Type;

public class CompRemitStmtId_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompRemitStmtId_Type compRemitStmtId_Type0 = new CompRemitStmtId_Type();
      compRemitStmtId_Type0.equals((Object) null);
  }
}
