/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.CompletedPmtCount_Type;

public class CompletedPmtCount_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompletedPmtCount_Type completedPmtCount_Type0 = new CompletedPmtCount_Type();
      Object object0 = new Object();
      completedPmtCount_Type0.equals(object0);
  }
}
