/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.CSPCustInfoReq_Type;

public class CSPCustInfoReq_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CSPCustInfoReq_Type cSPCustInfoReq_Type0 = new CSPCustInfoReq_Type();
      cSPCustInfoReq_Type0.equals((Object) null);
  }
}
