/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.MatDt_Type;

public class MatDt_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MatDt_Type matDt_Type0 = new MatDt_Type();
      matDt_Type0.equals((Object) null);
  }
}
