/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.OrigPmtDueDt_Type;

public class OrigPmtDueDt_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OrigPmtDueDt_Type origPmtDueDt_Type0 = new OrigPmtDueDt_Type();
      origPmtDueDt_Type0.equals((Object) null);
  }
}
