/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.simpletype.StopChkStatusCode_Type;

public class StopChkStatusCode_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      StopChkStatusCode_Type stopChkStatusCode_Type0 = new StopChkStatusCode_Type();
      stopChkStatusCode_Type0.equals((Object) null);
  }
}
