/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util.json;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.json.JSONFactoryUtil;
import org.junit.BeforeClass;

public class JSONFactoryUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JSONFactoryUtil jSONFactoryUtil0 = new JSONFactoryUtil();
  }
}
