/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.journal.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.journal.model.JournalSearchConstants;
import org.junit.BeforeClass;

public class JournalSearchConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JournalSearchConstants journalSearchConstants0 = new JournalSearchConstants();
  }
}
