/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.util.SleepHelper;
import org.junit.BeforeClass;

public class SleepHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SleepHelper.sleep(1331L);
  }

  @Test
  public void test1()  throws Throwable  {
      SleepHelper sleepHelper0 = new SleepHelper();
      assertNotNull(sleepHelper0);
  }
}
