/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.migration.proxy;

import org.junit.Test;
import static org.junit.Assert.*;
import org.exolab.jms.tools.migration.proxy.MessageHandlerFactory;
import org.junit.BeforeClass;

public class MessageHandlerFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MessageHandlerFactory messageHandlerFactory0 = new MessageHandlerFactory();
      assertNotNull(messageHandlerFactory0);
  }
}
