/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.application;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.FileNotFoundException;
import net.sf.lavalamp.application.ApplicationPropertiesLoader;
import org.junit.BeforeClass;

public class ApplicationPropertiesLoaderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ApplicationPropertiesLoader applicationPropertiesLoader0 = new ApplicationPropertiesLoader();
      try {
        applicationPropertiesLoader0.load("");
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
        /*
         *  (No such file or directory)
         */
      }
  }
}
