/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.support.alto;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class AltoStepperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
