/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_0;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.upgrade.UpgradeException;
import com.liferay.portal.upgrade.v6_0_0.UpgradeGroup;
import org.junit.BeforeClass;

public class UpgradeGroupEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeGroup upgradeGroup0 = new UpgradeGroup();
      try {
        upgradeGroup0.upgrade();
        fail("Expecting exception: UpgradeException");
      } catch(UpgradeException e) {
        /*
         * java.lang.NullPointerException
         */
      }
  }
}
