/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_0;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_0_0.UpgradeShopping;
import org.junit.BeforeClass;

public class UpgradeShoppingEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeShopping upgradeShopping0 = new UpgradeShopping();
      try {
        upgradeShopping0.doUpgrade();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
