/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.business.actions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class RotateRightImageActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
