/*
 * This file was automatically generated by EvoSuite
 */

package it.pdfsam.plugin.merge.component;

import org.junit.Test;
import static org.junit.Assert.*;
import it.pdfsam.plugin.merge.component.JMergeToolTipHeader;
import javax.swing.table.TableColumnModel;
import org.junit.BeforeClass;

public class JMergeToolTipHeaderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JMergeToolTipHeader jMergeToolTipHeader0 = new JMergeToolTipHeader((TableColumnModel) null);
      jMergeToolTipHeader0.setToolTipStrings(jMergeToolTipHeader0.tool_tips);
      assertEquals(true, jMergeToolTipHeader0.isFocusable());
  }
}
