/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.translator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.translator.TranslatorPortlet;
import org.junit.BeforeClass;

public class TranslatorPortletEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TranslatorPortlet translatorPortlet0 = new TranslatorPortlet();
      assertNotNull(translatorPortlet0);
  }
}
