/*
 * This file was automatically generated by EvoSuite
 */

package org.heal.servlet.upload;

import org.junit.Test;
import static org.junit.Assert.*;
import org.heal.servlet.upload.ShowUploadFormAction;
import org.junit.BeforeClass;

public class ShowUploadFormActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShowUploadFormAction showUploadFormAction0 = new ShowUploadFormAction();
      boolean boolean0 = showUploadFormAction0.actionRequiresLogin();
      assertEquals(true, boolean0);
  }
}
