/*
 * This file was automatically generated by EvoSuite
 */

package freemind.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import freemind.controller.Controller;
import freemind.controller.MainToolBar;
import org.junit.BeforeClass;

public class MainToolBarEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MainToolBar mainToolBar0 = null;
      try {
        mainToolBar0 = new MainToolBar((Controller) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
