/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.webdav.methods;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.webdav.methods.HeadMethodImpl;
import org.junit.BeforeClass;

public class HeadMethodImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HeadMethodImpl headMethodImpl0 = new HeadMethodImpl();
      assertNotNull(headMethodImpl0);
  }
}
