/*
 * This file was automatically generated by EvoSuite
 */

package com.densebrain.rif.server.test;

import org.junit.Test;
import static org.junit.Assert.*;
import com.densebrain.rif.server.test.TestWS;
import org.junit.BeforeClass;

public class TestWSEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TestWS testWS0 = new TestWS();
  }
}
