/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.xbus.application;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sf.xbus.application.PreProcessor;
import org.junit.BeforeClass;

public class PreProcessorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PreProcessor preProcessor0 = new PreProcessor();
      assertNotNull(preProcessor0);
  }
}
