/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_1.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_0_1.util.DLFileVersionTable;
import org.junit.BeforeClass;

public class DLFileVersionTableEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DLFileVersionTable dLFileVersionTable0 = new DLFileVersionTable();
  }
}
