/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.socket;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class SocketManagedConnectionAcceptorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
