/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.client.net;

import org.junit.Test;
import static org.junit.Assert.*;
import org.exolab.jms.client.net.XAExceptionAdapter;
import org.junit.BeforeClass;

public class XAExceptionAdapterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XAExceptionAdapter xAExceptionAdapter0 = new XAExceptionAdapter();
      Class<Object> class0 = xAExceptionAdapter0.getTarget();
      assertEquals("javax.transaction.xa.XAException", class0.getCanonicalName());
  }
}
