/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util.format;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.format.PhoneNumberUtil;
import org.junit.BeforeClass;

public class PhoneNumberUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PhoneNumberUtil phoneNumberUtil0 = new PhoneNumberUtil();
  }
}
