/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.social;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.documentlibrary.social.DLActivityInterpreter;
import org.junit.BeforeClass;

public class DLActivityInterpreterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DLActivityInterpreter dLActivityInterpreter0 = new DLActivityInterpreter();
      String[] stringArray0 = dLActivityInterpreter0.getClassNames();
      assertNotNull(stringArray0);
  }
}
