/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.social;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.documentlibrary.social.DLActivityKeys;
import org.junit.BeforeClass;

public class DLActivityKeysEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DLActivityKeys dLActivityKeys0 = new DLActivityKeys();
  }
}
