/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.DivideInstruction;
import org.junit.BeforeClass;

public class DivideInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DivideInstruction divideInstruction0 = new DivideInstruction(1681);
      assertNotNull(divideInstruction0);
  }
}
