/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.asset.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.asset.service.http.AssetCategoryPropertyServiceHttp;
import org.junit.BeforeClass;

public class AssetCategoryPropertyServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AssetCategoryPropertyServiceHttp assetCategoryPropertyServiceHttp0 = new AssetCategoryPropertyServiceHttp();
      assertNotNull(assetCategoryPropertyServiceHttp0);
  }
}
