/*
 * This file was automatically generated by EvoSuite
 */

package org.jcvi.jillion.assembly.tigr.tasm;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class TasmContigBuilderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
