/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.mfw.HibernateExporter;
import org.junit.BeforeClass;

public class HibernateExporterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HibernateExporter hibernateExporter0 = new HibernateExporter();
  }
}
