/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.permission;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.permission.LayoutPrototypePermissionImpl;
import org.junit.BeforeClass;

public class LayoutPrototypePermissionImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutPrototypePermissionImpl layoutPrototypePermissionImpl0 = new LayoutPrototypePermissionImpl();
      assertNotNull(layoutPrototypePermissionImpl0);
  }
}
