/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.permission;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.service.permission.LayoutSetPrototypePermissionImpl;
import org.junit.BeforeClass;

public class LayoutSetPrototypePermissionImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutSetPrototypePermissionImpl layoutSetPrototypePermissionImpl0 = new LayoutSetPrototypePermissionImpl();
      assertNotNull(layoutSetPrototypePermissionImpl0);
  }
}
