/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.service.permission;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.security.auth.PrincipalException;
import com.liferay.portal.security.permission.PermissionChecker;
import com.liferay.portal.service.permission.RolePermissionImpl;
import org.junit.BeforeClass;

public class RolePermissionImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RolePermissionImpl rolePermissionImpl0 = new RolePermissionImpl();
      // Undeclared exception!
      try {
        rolePermissionImpl0.check((PermissionChecker) null, (-479L), "{XFw@_6'&~fI4!WG");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
