/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.logging;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class LogIteratorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
