/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.core.util.png;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.core.util.png.PngSignatureChunk;
import org.junit.BeforeClass;

public class PngSignatureChunkEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PngSignatureChunk pngSignatureChunk0 = new PngSignatureChunk();
      byte[] byteArray0 = pngSignatureChunk0.getChunkPayload();
      assertNotNull(byteArray0);
  }
}
