/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.application.ApplicationErrorWindow;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class ApplicationErrorWindowEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        ApplicationErrorWindow.createWindow((Throwable) null, "");
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
