/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.application.SimpleExceptionHandler;
import org.junit.BeforeClass;

public class ApplicationExceptionHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleExceptionHandler simpleExceptionHandler0 = new SimpleExceptionHandler();
  }
}
