/*
 * This file was automatically generated by EvoSuite
 */

package org.bouncycastle.asn1.misc;

import org.junit.Test;
import static org.junit.Assert.*;
import org.bouncycastle.asn1.DERIA5String;
import org.bouncycastle.asn1.misc.NetscapeRevocationURL;
import org.junit.BeforeClass;

public class NetscapeRevocationURLEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DERIA5String dERIA5String0 = new DERIA5String(byteArray0);
      NetscapeRevocationURL netscapeRevocationURL0 = new NetscapeRevocationURL(dERIA5String0);
      String string0 = netscapeRevocationURL0.toString();
      assertNotNull(string0);
      assertEquals("NetscapeRevocationURL: \u0000\u0000\u0000\u0000", string0);
  }
}
