/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.commons.business.listeners;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.commons.business.listeners.CompressCheckBoxItemListener;
import org.pdfsam.guiclient.commons.components.JPdfVersionCombo;

public class CompressCheckBoxItemListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompressCheckBoxItemListener compressCheckBoxItemListener0 = new CompressCheckBoxItemListener((JPdfVersionCombo) null);
  }
}
