/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.social.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.social.model.SocialActivityConstants;
import org.junit.BeforeClass;

public class SocialActivityConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SocialActivityConstants socialActivityConstants0 = new SocialActivityConstants();
  }
}
