/*
 * This file was automatically generated by EvoSuite
 */

package org.jcvi.jillion.trace.fastq;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jcvi.jillion.core.qual.PhredQuality;
import org.jcvi.jillion.trace.fastq.SolexaUtil;
import org.junit.BeforeClass;

public class SolexaUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        SolexaUtil.convertPhredQualityToSolexaQuality((PhredQuality) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      PhredQuality phredQuality0 = SolexaUtil.convertSolexaQualityToPhredQuality((-16));
      assertNull(phredQuality0);
  }
}
