/*
 * This file was automatically generated by EvoSuite
 */

package teder;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import teder.Teder;

public class TederEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Teder teder0 = new Teder();
  }
}
