/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_1_0;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_1_0.UpgradeCamelCasePortletPreferences;
import org.junit.BeforeClass;

public class UpgradeCamelCasePortletPreferencesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeCamelCasePortletPreferences upgradeCamelCasePortletPreferences0 = new UpgradeCamelCasePortletPreferences();
      String string0 = upgradeCamelCasePortletPreferences0.getUpdatePortletPreferencesWhereClause();
      assertEquals("", string0);
  }
}
