/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_1_0;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_1_0.UpgradeResourcePermission;
import org.junit.BeforeClass;

public class UpgradeResourcePermissionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeResourcePermission upgradeResourcePermission0 = new UpgradeResourcePermission();
      try {
        upgradeResourcePermission0.doUpgrade();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
