/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_1_0;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_1_0.UpgradeNavigation;
import org.junit.BeforeClass;

public class UpgradeNavigationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeNavigation upgradeNavigation0 = new UpgradeNavigation();
      String[] stringArray0 = upgradeNavigation0.getPortletIds();
      assertNotNull(stringArray0);
  }
}
