/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_1_0;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.upgrade.UpgradeException;
import com.liferay.portal.upgrade.v6_1_0.UpgradeExpando;
import org.junit.BeforeClass;

public class UpgradeExpandoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UpgradeExpando upgradeExpando0 = new UpgradeExpando();
      try {
        upgradeExpando0.upgrade();
        fail("Expecting exception: UpgradeException");
      } catch(UpgradeException e) {
        /*
         * java.lang.NullPointerException
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      UpgradeExpando upgradeExpando0 = new UpgradeExpando();
      try {
        upgradeExpando0.updateColumnTypeSettings(9L, "Ma8MIr5BG");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
