/*
 * This file was automatically generated by EvoSuite
 */

package org.firebirdsql.jdbc;

import org.junit.Test;
import static org.junit.Assert.*;
import org.firebirdsql.jdbc.FBConnectionDefaults;
import org.junit.BeforeClass;

public class FBConnectionDefaultsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FBConnectionDefaults fBConnectionDefaults0 = new FBConnectionDefaults();
  }
}
