/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.plugins;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.statsbiblioteket.summa.plugins.OpenUrlEscape;
import org.junit.BeforeClass;

public class OpenUrlEscapeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenUrlEscape openUrlEscape0 = new OpenUrlEscape();
      assertNotNull(openUrlEscape0);
  }

  @Test
  public void test1()  throws Throwable  {
      String string0 = OpenUrlEscape.escape("");
      assertNotNull(string0);
      assertEquals("", string0);
  }
}
