/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.net.upnp.impl.device;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class UPnPRootDeviceImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
