/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.client.session.action;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.squirrel_sql.client.session.IObjectTreeAPI;
import net.sourceforge.squirrel_sql.client.session.action.RefreshObjectTreeCommand;
import org.junit.BeforeClass;

public class RefreshObjectTreeCommandEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RefreshObjectTreeCommand refreshObjectTreeCommand0 = null;
      try {
        refreshObjectTreeCommand0 = new RefreshObjectTreeCommand((IObjectTreeAPI) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * IObjectTreeAPI == null
         */
      }
  }
}
