/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.permission;

import org.junit.Test;
import static org.junit.Assert.*;
import org.jsecurity.authz.permission.WildcardPermissionResolver;
import org.junit.BeforeClass;

public class WildcardPermissionResolverEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      WildcardPermissionResolver wildcardPermissionResolver0 = new WildcardPermissionResolver();
      // Undeclared exception!
      try {
        wildcardPermissionResolver0.resolvePermission("");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Wildcard string cannot be null or empty. Make sure permission strings are properly formatted.
         */
      }
  }
}
