/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class ProgressDialogEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
