/*
 * This file was automatically generated by EvoSuite
 */

package macaw.io;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.File;
import java.io.FileNotFoundException;
import macaw.io.ImportVariables;
import org.junit.BeforeClass;

public class ImportVariablesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ImportVariables importVariables0 = new ImportVariables();
      try {
        importVariables0.readFile((File) null);
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
        /*
         * C:\\macaw_import\\Variables.txt (No such file or directory)
         */
      }
  }
}
