/*
 * This file was automatically generated by EvoSuite
 */

package com.gbshape.dbe.sqlserver;

import org.junit.Test;
import static org.junit.Assert.*;
import com.gbshape.dbe.sqlserver.SqlserverDataBaseList;
import com.gbshape.dbe.struts.bean.DBDataBean;
import org.junit.BeforeClass;

public class SqlserverDataBaseListEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SqlserverDataBaseList sqlserverDataBaseList0 = new SqlserverDataBaseList();
      DBDataBean dBDataBean0 = new DBDataBean();
      sqlserverDataBaseList0.getDataBaseList(dBDataBean0);
  }
}
