/*
 * This file was automatically generated by EvoSuite
 */

package weka.gui.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import java.beans.EventSetDescriptor;
import org.junit.BeforeClass;
import weka.gui.beans.TextViewerBeanInfo;

public class TextViewerBeanInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TextViewerBeanInfo textViewerBeanInfo0 = new TextViewerBeanInfo();
      EventSetDescriptor[] eventSetDescriptorArray0 = textViewerBeanInfo0.getEventSetDescriptors();
      assertNotNull(eventSetDescriptorArray0);
  }
}
