/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.LTSTransferHandler;
import org.junit.BeforeClass;

public class LTSTransferHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LTSTransferHandler.initializeClass();
  }
}
