/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.security.permission;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.security.permission.ActionKeys;
import org.junit.BeforeClass;

public class ActionKeysEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ActionKeys actionKeys0 = new ActionKeys();
  }
}
