/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.element.IndustId;

public class IndustIdEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IndustId industId0 = new IndustId();
      industId0.equals((Object) "_d[z|OU]4{vO,");
  }
}
