/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.element.InvoiceAdj;

public class InvoiceAdjEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InvoiceAdj invoiceAdj0 = new InvoiceAdj();
      invoiceAdj0.equals((Object) "org.sourceforge.ifx.framework.element.CurConvertRule = {\n  String = NULL\n}");
  }
}
