/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.element;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.element.LegalName;

public class LegalNameEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LegalName legalName0 = new LegalName();
      legalName0.equals((Object) null);
  }
}
