/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.mobile.device.rulegroup.action.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.mobile.device.rulegroup.action.impl.SimpleRedirectActionHandler;
import org.junit.BeforeClass;

public class BaseRedirectActionHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleRedirectActionHandler simpleRedirectActionHandler0 = new SimpleRedirectActionHandler();
      assertEquals("com.liferay.portal.mobile.device.rulegroup.action.impl.SimpleRedirectActionHandler", simpleRedirectActionHandler0.getType());
  }
}
