/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.plugin.split.components;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.commons.panels.JPdfSelectionPanel;
import org.pdfsam.plugin.split.components.JBLevelCombo;

public class JBLevelComboEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JBLevelCombo jBLevelCombo0 = null;
      try {
        jBLevelCombo0 = new JBLevelCombo((JPdfSelectionPanel) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
