/*
 * This file was automatically generated by EvoSuite
 */

package accessories.plugins;

import org.junit.Test;
import static org.junit.Assert.*;
import accessories.plugins.FormatNewNodes;
import freemind.modes.MindMap;
import freemind.modes.ModeController;
import org.junit.BeforeClass;

public class FormatNewNodesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FormatNewNodes formatNewNodes0 = null;
      try {
        formatNewNodes0 = new FormatNewNodes((ModeController) null, (MindMap) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
