/*
 * This file was automatically generated by EvoSuite
 */

package accessories.plugins;

import org.junit.Test;
import static org.junit.Assert.*;
import accessories.plugins.SaveAll;
import org.junit.BeforeClass;

public class SaveAllEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SaveAll saveAll0 = new SaveAll();
      assertNull(saveAll0.getName());
  }
}
