/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.impl.ContactImpl;
import org.junit.BeforeClass;

public class ContactImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ContactImpl contactImpl0 = null;
      try {
        contactImpl0 = new ContactImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.model.impl.ContactImpl
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ContactImpl contactImpl0 = null;
      try {
        contactImpl0 = new ContactImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.model.impl.ContactImpl
         */
      }
  }
}
