/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.impl.CountryImpl;
import org.evosuite.testcase.TestCaseExecutor;
import org.junit.BeforeClass;

public class CountryBaseImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CountryImpl countryImpl0 = null;
      try {
        countryImpl0 = new CountryImpl();
        fail("Expecting exception: ExceptionInInitializerError");
      } catch(ExceptionInInitializerError e) {
      }
  }
}
