/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.impl.LayoutBranchImpl;
import org.junit.BeforeClass;

public class LayoutBranchBaseImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutBranchImpl layoutBranchImpl0 = null;
      try {
        layoutBranchImpl0 = new LayoutBranchImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.model.impl.LayoutBranchImpl
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LayoutBranchImpl layoutBranchImpl0 = null;
      try {
        layoutBranchImpl0 = new LayoutBranchImpl();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.model.impl.LayoutBranchImpl
         */
      }
  }
}
