/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.json.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.json.transformer.FlexjsonObjectJSONTransformer;
import flexjson.PathExpression;
import java.util.LinkedList;
import org.junit.BeforeClass;

public class FlexjsonObjectJSONTransformerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FlexjsonObjectJSONTransformer flexjsonObjectJSONTransformer0 = new FlexjsonObjectJSONTransformer();
      LinkedList<PathExpression> linkedList0 = new LinkedList<PathExpression>();
      flexjsonObjectJSONTransformer0.transform((Object) linkedList0);
  }
}
