/*
 * This file was automatically generated by EvoSuite
 */

package fr.pingtimeout.jtail.gui.view;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class HighlightDialogEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
