/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.probeframework.javaclient.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.probeframework.javaclient.protocol.Configuration;
import org.junit.BeforeClass;

public class ConfigurationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Configuration.configure();
  }

  @Test
  public void test1()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      assertEquals((-1), configuration0.port);
  }
}
