/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.gui.panels;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.gui.panels.JStatusPanel;

public class JStatusPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JStatusPanel jStatusPanel0 = null;
      try {
        jStatusPanel0 = new JStatusPanel();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
