/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application.data.coll;

import org.junit.Test;
import static org.junit.Assert.*;
import com.lts.application.data.coll.ADCEvent;
import org.junit.BeforeClass;

public class ADCEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ADCEvent aDCEvent0 = new ADCEvent();
  }
}
