/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.client.preferences.codereformat;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class FormatSqlControllerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
