/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.plugins.dbcopy.event;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.squirrel_sql.plugins.dbcopy.SessionInfoProvider;
import net.sourceforge.squirrel_sql.plugins.dbcopy.event.CopyEvent;
import org.junit.BeforeClass;

public class AbstractCopyEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CopyEvent copyEvent0 = new CopyEvent((SessionInfoProvider) null);
      SessionInfoProvider sessionInfoProvider0 = copyEvent0.getSessionInfoProvider();
      assertNull(sessionInfoProvider0);
  }
}
