/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.plugins.dbcopy.event;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.squirrel_sql.plugins.dbcopy.DBCopyPlugin;
import net.sourceforge.squirrel_sql.plugins.dbcopy.SessionInfoProvider;
import net.sourceforge.squirrel_sql.plugins.dbcopy.event.AnalysisEvent;
import org.junit.BeforeClass;

public class AnalysisEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      AnalysisEvent analysisEvent0 = new AnalysisEvent((SessionInfoProvider) dBCopyPlugin0);
  }
}
