/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.upgrade.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.upgrade.util.ValueMapperUtil;
import org.junit.BeforeClass;

public class ValueMapperUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ValueMapperUtil valueMapperUtil0 = new ValueMapperUtil();
      assertNotNull(valueMapperUtil0);
  }
}
