/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.plugin.vpagereorder.GUI;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.plugin.vpagereorder.GUI.VPageReorderMainGUI;

public class VPageReorderMainGUIEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      VPageReorderMainGUI vPageReorderMainGUI0 = null;
      try {
        vPageReorderMainGUI0 = new VPageReorderMainGUI();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
