/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.store;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class AdvancedFileSystemStoreEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
