/*
 * This file was automatically generated by EvoSuite
 */

package dk.statsbiblioteket.summa.common.unittest;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.statsbiblioteket.summa.common.unittest.LuceneTestHelper;
import org.junit.BeforeClass;

public class LuceneTestHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LuceneTestHelper luceneTestHelper0 = new LuceneTestHelper();
      assertEquals("null(dk.statsbiblioteket.summa.common.unittest.LuceneTestHelper)", luceneTestHelper0.toString());
  }
}
