/*
 * This file was automatically generated by EvoSuite
 */

package corina.graph;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.graph.Axis;
import corina.graph.GraphInfo;
import org.junit.BeforeClass;

public class AxisEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Axis axis0 = null;
      try {
        axis0 = new Axis((GraphInfo) null, (-16));
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
