/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.core.subs;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.core.subs.SubscriptionUtils;
import org.junit.BeforeClass;

public class SubscriptionUtilsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SubscriptionUtils subscriptionUtils0 = new SubscriptionUtils();
      assertNotNull(subscriptionUtils0);
  }
}
