/*
 * This file was automatically generated by EvoSuite
 */

package module;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import java.net.UnknownHostException;
import module.IRCSession;
import org.junit.BeforeClass;

public class IRCSessionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IRCSession iRCSession0 = null;
      try {
        iRCSession0 = new IRCSession((String) null, (String) null, (-1689));
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * port out of range:-1689
         */
      }
  }
}
