/*
 * This file was automatically generated by EvoSuite
 */

package module;

import org.junit.Test;
import static org.junit.Assert.*;
import module.Loader;
import org.junit.BeforeClass;

public class LoaderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Loader loader0 = new Loader();
  }
}
