/*
 * This file was automatically generated by EvoSuite
 */

package fr.pingtimeout.jtail.util;

import org.junit.Test;
import static org.junit.Assert.*;
import fr.pingtimeout.jtail.util.JTailConstants;
import org.junit.BeforeClass;

public class JTailConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTailConstants jTailConstants0 = new JTailConstants();
  }
}
