/*
 * This file was automatically generated by EvoSuite
 */

package common;

import org.junit.Test;
import static org.junit.Assert.*;
import common.Constants;
import org.junit.BeforeClass;

public class ConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Constants constants0 = new Constants();
  }
}
