/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.documentlibrary.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.repository.model.FileVersion;
import com.liferay.portlet.documentlibrary.util.VideoProcessorUtil;
import org.junit.BeforeClass;

public class VideoProcessorUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      VideoProcessorUtil videoProcessorUtil0 = new VideoProcessorUtil();
      assertNotNull(videoProcessorUtil0);
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        VideoProcessorUtil.isVideoSupported((FileVersion) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
