/*
 * This file was automatically generated by EvoSuite
 */

package org.heal.servlet.userreview;

import org.junit.Test;
import static org.junit.Assert.*;
import org.heal.servlet.userreview.ShowUserReviewAction;
import org.junit.BeforeClass;

public class ShowUserReviewActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShowUserReviewAction showUserReviewAction0 = new ShowUserReviewAction();
      boolean boolean0 = showUserReviewAction0.actionRequiresLogin();
      assertEquals(true, boolean0);
  }
}
