/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.utils.filters;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.utils.filters.PdfFilter;

public class PdfFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PdfFilter pdfFilter0 = new PdfFilter();
      String string0 = pdfFilter0.getAcceptedExtension();
      assertEquals("pdf", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      PdfFilter pdfFilter0 = new PdfFilter(false);
      assertEquals("pdf", pdfFilter0.getAcceptedExtension());
  }

  @Test
  public void test2()  throws Throwable  {
      PdfFilter pdfFilter0 = new PdfFilter();
      String string0 = pdfFilter0.getDescription();
      assertEquals("pdf files", string0);
  }
}
