/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.fw.sql;

import org.junit.Test;
import static org.junit.Assert.*;
import java.beans.IntrospectionException;
import java.beans.PropertyDescriptor;
import net.sourceforge.squirrel_sql.fw.sql.DatabaseObjectInfoBeanInfo;
import org.junit.BeforeClass;

public class DatabaseObjectInfoBeanInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatabaseObjectInfoBeanInfo databaseObjectInfoBeanInfo0 = new DatabaseObjectInfoBeanInfo();
      PropertyDescriptor[] propertyDescriptorArray0 = databaseObjectInfoBeanInfo0.getPropertyDescriptors();
      assertNotNull(propertyDescriptorArray0);
  }
}
