/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.swing.statistics;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.swing.MainFrame;
import de.huxhorn.lilith.swing.statistics.NinetyDaysProducer;
import org.junit.BeforeClass;

public class NinetyDaysProducerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      NinetyDaysProducer ninetyDaysProducer0 = new NinetyDaysProducer((MainFrame) null);
  }
}
