/*
 * This file was automatically generated by EvoSuite
 */

package weka.gui.graphvisualizer;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class GraphVisualizerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
