/*
 * This file was automatically generated by EvoSuite
 */

package org.pdfsam.guiclient.plugins;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.pdfsam.guiclient.exceptions.PluginException;
import org.pdfsam.guiclient.plugins.PlugInsLoader;

public class PlugInsLoaderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PlugInsLoader plugInsLoader0 = null;
      try {
        plugInsLoader0 = new PlugInsLoader((String) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      PlugInsLoader plugInsLoader0 = null;
      try {
        plugInsLoader0 = new PlugInsLoader("");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      PlugInsLoader plugInsLoader0 = new PlugInsLoader(".");
      // Undeclared exception!
      try {
        plugInsLoader0.loadPlugins();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      PlugInsLoader plugInsLoader0 = null;
      try {
        plugInsLoader0 = new PlugInsLoader("_[<x}@M,]x]=8");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
