/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.SetUtil;
import org.junit.BeforeClass;

public class SetUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SetUtil setUtil0 = new SetUtil();
  }
}
