/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.ThirdPartyThreadLocalRegistry;
import org.junit.BeforeClass;

public class ThirdPartyThreadLocalRegistryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ThirdPartyThreadLocalRegistry thirdPartyThreadLocalRegistry0 = new ThirdPartyThreadLocalRegistry();
      assertNotNull(thirdPartyThreadLocalRegistry0);
  }

  @Test
  public void test1()  throws Throwable  {
      ThirdPartyThreadLocalRegistry.resetThreadLocals();
  }
}
