/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.dynamicdatalists.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.dynamicdatalists.model.impl.DDLRecordVersionImpl;
import org.evosuite.testcase.TestCaseExecutor;
import org.junit.BeforeClass;

public class DDLRecordVersionBaseImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DDLRecordVersionImpl dDLRecordVersionImpl0 = null;
      try {
        dDLRecordVersionImpl0 = new DDLRecordVersionImpl();
        fail("Expecting exception: ExceptionInInitializerError");
      } catch(ExceptionInInitializerError e) {
      }
  }
}
