/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.servlet;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.servlet.FacebookServlet;
import org.junit.BeforeClass;

public class FacebookServletEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FacebookServlet facebookServlet0 = new FacebookServlet();
  }
}
