/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.servlet;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.servlet.PortalSessionListener;
import org.junit.BeforeClass;

public class PortalSessionListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PortalSessionListener portalSessionListener0 = new PortalSessionListener();
      assertNotNull(portalSessionListener0);
  }
}
