/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.simpletype.Amt_Type;

public class Amt_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Amt_Type amt_Type0 = new Amt_Type();
      amt_Type0.equals((Object) null);
  }
}
