/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.remit.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.remit.simpletype.StatusModBy_Type;

public class StatusModBy_TypeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      StatusModBy_Type statusModBy_Type0 = new StatusModBy_Type();
      statusModBy_Type0.equals((Object) null);
  }
}
