/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.jul.xml;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.jul.xml.LoggingEventReader;
import org.junit.BeforeClass;

public class LoggingEventReaderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoggingEventReader loggingEventReader0 = new LoggingEventReader();
  }
}
