/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw.bundle.server.plugins.webui.eventlistpage;

import org.junit.Test;
import static org.junit.Assert.*;
import fi.vtt.noen.mfw.bundle.server.plugins.persistence.PersistencePlugin;
import fi.vtt.noen.mfw.bundle.server.plugins.webui.eventlistpage.EventHistoryDataProvider;
import fi.vtt.noen.mfw.bundle.server.shared.datamodel.ServerEvent;
import org.junit.BeforeClass;

public class EventHistoryDataProviderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      EventHistoryDataProvider eventHistoryDataProvider0 = null;
      try {
        eventHistoryDataProvider0 = new EventHistoryDataProvider((PersistencePlugin) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class fi.vtt.noen.mfw.bundle.server.plugins.webui.eventlistpage.EventHistoryDataProvider
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      EventHistoryDataProvider eventHistoryDataProvider0 = null;
      try {
        eventHistoryDataProvider0 = new EventHistoryDataProvider((PersistencePlugin) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class fi.vtt.noen.mfw.bundle.server.plugins.webui.eventlistpage.EventHistoryDataProvider
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      EventHistoryDataProvider eventHistoryDataProvider0 = null;
      try {
        eventHistoryDataProvider0 = new EventHistoryDataProvider((PersistencePlugin) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class fi.vtt.noen.mfw.bundle.server.plugins.webui.eventlistpage.EventHistoryDataProvider
         */
      }
  }
}
