/*
 * This file was automatically generated by EvoSuite
 */

package com.mentorgen.tools.profile.output;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mentorgen.tools.profile.output.ClassAllocComparator;
import com.mentorgen.tools.profile.runtime.ClassAllocation;
import org.junit.BeforeClass;

public class ClassAllocComparatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ClassAllocComparator classAllocComparator0 = new ClassAllocComparator();
      // Undeclared exception!
      try {
        classAllocComparator0.compare((ClassAllocation) null, (ClassAllocation) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
