/*
 * This file was automatically generated by EvoSuite
 */

package com.mentorgen.tools.profile.output;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mentorgen.tools.profile.output.HolderComparator;
import org.junit.BeforeClass;

public class HolderComparatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HolderComparator holderComparator0 = new HolderComparator();
      assertNotNull(holderComparator0);
  }
}
