/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.data.access.protobuf;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.data.access.protobuf.CompressingAccessEventWrapperProtobufCodec;
import org.junit.BeforeClass;

public class CompressingAccessEventWrapperProtobufCodecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompressingAccessEventWrapperProtobufCodec compressingAccessEventWrapperProtobufCodec0 = new CompressingAccessEventWrapperProtobufCodec();
  }
}
