/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.util.xml;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.util.xml.ElementIdentifier;
import org.junit.BeforeClass;

public class ElementIdentifierEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ElementIdentifier elementIdentifier0 = new ElementIdentifier("", "");
      String string0 = elementIdentifier0.getIdentifierName();
      assertEquals("", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      ElementIdentifier elementIdentifier0 = new ElementIdentifier("", "");
      String string0 = elementIdentifier0.getElementName();
      assertEquals("", string0);
  }
}
