/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_0.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.upgrade.util.DateUpgradeColumnImpl;
import com.liferay.portal.kernel.upgrade.util.UpgradeColumn;
import com.liferay.portal.upgrade.v6_0_0.util.DLFileEntryTitleUpgradeColumnImpl;
import org.junit.BeforeClass;

public class DLFileEntryTitleUpgradeColumnImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DateUpgradeColumnImpl dateUpgradeColumnImpl0 = new DateUpgradeColumnImpl("");
      DLFileEntryTitleUpgradeColumnImpl dLFileEntryTitleUpgradeColumnImpl0 = new DLFileEntryTitleUpgradeColumnImpl((UpgradeColumn) dateUpgradeColumnImpl0, "");
      assertEquals("", dLFileEntryTitleUpgradeColumnImpl0.getName());
  }
}
