/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_0.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_0_0.util.LayoutTable;
import org.junit.BeforeClass;

public class LayoutTableEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutTable layoutTable0 = new LayoutTable();
  }
}
