/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.upgrade.v6_0_0.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.upgrade.v6_0_0.util.SocialRelationTable;
import org.junit.BeforeClass;

public class SocialRelationTableEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SocialRelationTable socialRelationTable0 = new SocialRelationTable();
  }
}
