/*
 * This file was automatically generated by EvoSuite
 */

package com.eteks.sweethome3d;

import org.junit.Test;
import static org.junit.Assert.*;
import com.eteks.sweethome3d.MacOSXConfiguration;
import org.junit.BeforeClass;

public class MacOSXConfigurationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MacOSXConfiguration macOSXConfiguration0 = new MacOSXConfiguration();
      assertNotNull(macOSXConfiguration0);
  }
}
