/*
 * This file was automatically generated by EvoSuite
 */

package com.eteks.sweethome3d;

import org.junit.Test;
import static org.junit.Assert.*;
import com.eteks.sweethome3d.SweetHome3DBootstrap;
import org.junit.BeforeClass;

public class SweetHome3DBootstrapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SweetHome3DBootstrap sweetHome3DBootstrap0 = new SweetHome3DBootstrap();
  }
}
