/*
 * This file was automatically generated by EvoSuite
 */

package com.eteks.sweethome3d.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import com.eteks.sweethome3d.model.UserPreferences;
import com.eteks.sweethome3d.swing.LabelPanel;
import com.eteks.sweethome3d.viewcontroller.LabelController;
import org.junit.BeforeClass;

public class LabelPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LabelPanel labelPanel0 = null;
      try {
        labelPanel0 = new LabelPanel(false, (UserPreferences) null, (LabelController) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
