/*
 * This file was automatically generated by EvoSuite
 */

package com.eteks.sweethome3d.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import com.eteks.sweethome3d.model.UserPreferences;
import com.eteks.sweethome3d.swing.PageSetupPanel;
import com.eteks.sweethome3d.viewcontroller.PageSetupController;
import org.junit.BeforeClass;

public class PageSetupPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PageSetupPanel pageSetupPanel0 = null;
      try {
        pageSetupPanel0 = new PageSetupPanel((UserPreferences) null, (PageSetupController) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
