/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain002.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain002.simpletype.BEIIdentifier;

public class BEIIdentifierEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BEIIdentifier bEIIdentifier0 = new BEIIdentifier();
      bEIIdentifier0.equals((Object) null);
  }
}
