/*
 * This file was automatically generated by EvoSuite
 */

package org.sourceforge.ifx.framework.pain002.simpletype;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.sourceforge.ifx.framework.pain002.simpletype.PriorityCode;

public class PriorityCodeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PriorityCode priorityCode0 = new PriorityCode();
      priorityCode0.equals((Object) null);
  }
}
