/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.ratings.model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.ratings.model.impl.RatingsStatsImpl;
import org.evosuite.testcase.TestCaseExecutor;
import org.junit.BeforeClass;

public class RatingsStatsImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RatingsStatsImpl ratingsStatsImpl0 = null;
      try {
        ratingsStatsImpl0 = new RatingsStatsImpl();
        fail("Expecting exception: ExceptionInInitializerError");
      } catch(ExceptionInInitializerError e) {
      }
  }
}
