/*
 * This file was automatically generated by EvoSuite
 */

package com.aelitis.azureus.ui.skin;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.ui.skin.SkinConstants;
import org.junit.BeforeClass;

public class SkinConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SkinConstants skinConstants0 = new SkinConstants();
  }
}
