/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.messageboards.util.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.messageboards.util.comparator.MessageThreadComparator;
import org.junit.BeforeClass;

public class MessageThreadComparatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MessageThreadComparator messageThreadComparator0 = new MessageThreadComparator();
      assertNotNull(messageThreadComparator0);
  }
}
