/*
 * This file was automatically generated by EvoSuite
 */

package com.allenstudio.ir.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import com.allenstudio.ir.ui.DatePickerPane;
import com.allenstudio.ir.ui.calendar.DateChooser;
import java.util.GregorianCalendar;
import org.junit.BeforeClass;

public class DatePickerPaneEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatePickerPane datePickerPane0 = new DatePickerPane();
      DateChooser dateChooser0 = datePickerPane0.getDateChooser();
      assertEquals(false, dateChooser0.getAutoscrolls());
  }

  @Test
  public void test1()  throws Throwable  {
      DatePickerPane datePickerPane0 = new DatePickerPane();
      GregorianCalendar gregorianCalendar0 = datePickerPane0.reportSelectedDate();
      assertNull(gregorianCalendar0);
  }
}
