/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.json;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.json.JSONInit;
import org.junit.BeforeClass;

public class JSONInitEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JSONInit jSONInit0 = new JSONInit();
      assertNotNull(jSONInit0);
  }

  @Test
  public void test1()  throws Throwable  {
      JSONInit.init();
  }
}
