/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import org.exolab.jms.tools.admin.CreateUserDialog;
import org.junit.BeforeClass;

public class CreateUserDialogEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CreateUserDialog createUserDialog0 = CreateUserDialog.instance();
      assertNull(createUserDialog0);
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        CreateUserDialog.create((JFrame) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
