/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.swing.JTree;
import org.exolab.jms.tools.admin.OpenJMSQueue;
import org.junit.BeforeClass;

public class OpenJMSQueueEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Object[] objectArray0 = new Object[20];
      JTree jTree0 = new JTree(objectArray0);
      OpenJMSQueue openJMSQueue0 = new OpenJMSQueue("!", jTree0);
      openJMSQueue0.update();
      assertEquals(0, openJMSQueue0.getChildCount());
  }
}
