/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import org.exolab.jms.tools.admin.OpenJMSDestination;
import org.junit.BeforeClass;

public class OpenJMSDestinationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        OpenJMSDestination.getInstanceSelected();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
