/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.test;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.test.NewJVMJUnitTestRunner;
import org.junit.BeforeClass;

public class NewJVMJUnitTestRunnerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      NewJVMJUnitTestRunner.attachProcess("j5=");
      NewJVMJUnitTestRunner.attachProcess("j5=");
  }
}
