/*
 * This file was automatically generated by EvoSuite
 */

package dsachat;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class TestEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      dsachat.Test test0 = new dsachat.Test();
  }
}
