/*
 * This file was automatically generated by EvoSuite
 */

package org.gudy.azureus2.ui.swt.mainwindow;

import org.junit.Test;
import static org.junit.Assert.*;
import com.aelitis.azureus.ui.IUIIntializer;
import org.eclipse.swt.widgets.Display;
import org.gudy.azureus2.ui.swt.mainwindow.SplashWindow;
import org.junit.BeforeClass;

public class SplashWindowEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SplashWindow.create((Display) null, (IUIIntializer) null);
  }
}
