/*
 * This file was automatically generated by EvoSuite
 */

package org.heal.servlet.search;

import org.junit.Test;
import static org.junit.Assert.*;
import org.heal.servlet.search.AdvSearchAction;
import org.junit.BeforeClass;

public class AdvSearchActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AdvSearchAction advSearchAction0 = new AdvSearchAction();
      boolean boolean0 = advSearchAction0.actionRequiresLogin();
      assertEquals(false, boolean0);
  }
}
