/*
 * This file was automatically generated by EvoSuite
 */

package dash.examples.component;

import org.junit.Test;
import static org.junit.Assert.*;
import dash.examples.component.TestComponent;
import org.junit.BeforeClass;

public class TestComponentEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TestComponent testComponent0 = new TestComponent();
  }
}
