/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.kernel.search;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.search.SearchContextFactory;
import org.junit.BeforeClass;

public class SearchContextFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SearchContextFactory searchContextFactory0 = new SearchContextFactory();
      assertNotNull(searchContextFactory0);
  }
}
