/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.tools.deploy;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.tools.deploy.LayoutTemplateDeployer;
import org.junit.BeforeClass;

public class LayoutTemplateDeployerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutTemplateDeployer layoutTemplateDeployer0 = new LayoutTemplateDeployer();
      layoutTemplateDeployer0.getPluginType();
  }
}
