/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.audit;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.audit.AuditRouterProxyBean;
import com.liferay.portal.kernel.audit.AuditMessage;
import org.junit.BeforeClass;

public class AuditRouterProxyBeanEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AuditRouterProxyBean auditRouterProxyBean0 = new AuditRouterProxyBean();
      // Undeclared exception!
      try {
        auditRouterProxyBean0.route((AuditMessage) null);
        fail("Expecting exception: UnsupportedOperationException");
      } catch(UnsupportedOperationException e) {
      }
  }
}
