/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.LayoutTypeArticleConfigurationDeleteAction;
import org.junit.BeforeClass;

public class LayoutTypeArticleConfigurationDeleteActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutTypeArticleConfigurationDeleteAction layoutTypeArticleConfigurationDeleteAction0 = new LayoutTypeArticleConfigurationDeleteAction();
      assertNotNull(layoutTypeArticleConfigurationDeleteAction0);
  }
}
