/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.LayoutSet;
import com.liferay.portal.model.LayoutSetListener;
import org.junit.BeforeClass;

public class LayoutSetListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutSetListener layoutSetListener0 = new LayoutSetListener();
      // Undeclared exception!
      try {
        layoutSetListener0.onAfterRemove((LayoutSet) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LayoutSetListener layoutSetListener0 = new LayoutSetListener();
      // Undeclared exception!
      try {
        layoutSetListener0.onAfterUpdate((LayoutSet) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
