/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.Layout;
import com.liferay.portal.model.LayoutStagingHandler;
import org.junit.BeforeClass;

public class LayoutStagingHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LayoutStagingHandler layoutStagingHandler0 = null;
      try {
        layoutStagingHandler0 = new LayoutStagingHandler((Layout) null);
        fail("Expecting exception: IllegalStateException");
      } catch(IllegalStateException e) {
        /*
         * java.lang.NullPointerException
         */
      }
  }
}
