/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.model.ModelHintsConstants;
import org.junit.BeforeClass;

public class ModelHintsConstantsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ModelHintsConstants modelHintsConstants0 = new ModelHintsConstants();
  }
}
