/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.squirrel_sql.client.util.codereformat;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.squirrel_sql.client.util.codereformat.CommentSpec;
import org.junit.BeforeClass;

public class CommentSpecEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CommentSpec commentSpec0 = new CommentSpec((String) null, (String) null);
      assertNotNull(commentSpec0);
  }
}
