/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portal.struts;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.struts.PortletActionServlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import org.junit.BeforeClass;

public class PortletActionServletEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PortletActionServlet portletActionServlet0 = null;
      try {
        portletActionServlet0 = new PortletActionServlet();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.liferay.portal.struts.PortletActionServlet
         */
      }
  }
}
