/*
 * This file was automatically generated by EvoSuite
 */

package corina.map.projections;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.map.Point3D;
import corina.map.View;
import corina.map.projections.RectangularProjection;
import corina.site.Location;
import java.awt.Point;
import org.evosuite.testcase.CodeUnderTestException;
import org.junit.BeforeClass;

public class RectangularProjectionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      View view0 = new View();
      RectangularProjection rectangularProjection0 = new RectangularProjection(view0);
      Point3D point3D0 = new Point3D();
  }

  @Test
  public void test1()  throws Throwable  {
      View view0 = new View();
      RectangularProjection rectangularProjection0 = new RectangularProjection(view0);
      Point point0 = new Point();
  }
}
