/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.swing.preferences;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.swing.preferences.PreferencesDialog;
import de.huxhorn.lilith.swing.preferences.SourcesPanel;
import java.awt.HeadlessException;
import org.junit.BeforeClass;

public class SourcesPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SourcesPanel sourcesPanel0 = null;
      try {
        sourcesPanel0 = new SourcesPanel((PreferencesDialog) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
