/*
 * This file was automatically generated by EvoSuite
 */

package de.huxhorn.lilith.swing.preferences;

import org.junit.Test;
import static org.junit.Assert.*;
import de.huxhorn.lilith.swing.preferences.SourceNameTableModel;
import java.util.Hashtable;
import java.util.Map;
import org.junit.BeforeClass;

public class SourceNameTableModelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Hashtable<String, String> hashtable0 = new Hashtable<String, String>();
      SourceNameTableModel sourceNameTableModel0 = new SourceNameTableModel((Map<String, String>) hashtable0);
      sourceNameTableModel0.getValueAt(0, 0);
  }
}
