/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.xbus.technical.misc;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sf.xbus.base.xbussystem.XBUSSystem;
import net.sf.xbus.technical.misc.ProgramSender;
import org.junit.BeforeClass;

public class ProgramSenderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ProgramSender programSender0 = new ProgramSender((XBUSSystem) null);
      String string0 = programSender0.getType();
      assertEquals("Text", string0);
  }
}
