/*
 * This file was automatically generated by EvoSuite
 */

package fi.vtt.noen.mfw.bundle.server.plugins.webui.probeparameterpage;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class ProbeParameterPageEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
