/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.trash.service.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portlet.trash.service.http.TrashEntryServiceHttp;
import org.junit.BeforeClass;

public class TrashEntryServiceHttpEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TrashEntryServiceHttp trashEntryServiceHttp0 = new TrashEntryServiceHttp();
      assertNotNull(trashEntryServiceHttp0);
  }
}
