/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web.tags;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.servlet.jsp.JspException;
import org.jsecurity.web.tags.AuthenticatedTag;
import org.junit.BeforeClass;

public class AuthenticatedTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AuthenticatedTag authenticatedTag0 = new AuthenticatedTag();
      int int0 = authenticatedTag0.doStartTag();
      assertEquals(0, int0);
  }
}
