/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web.tags;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.servlet.jsp.JspException;
import org.jsecurity.web.tags.HasAnyRolesTag;
import org.junit.BeforeClass;

public class SecureTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HasAnyRolesTag hasAnyRolesTag0 = new HasAnyRolesTag();
      int int0 = hasAnyRolesTag0.doStartTag();
      assertEquals(0, int0);
  }
}
