/*
 * This file was automatically generated by EvoSuite
 */

package com.liferay.portlet.journal.messaging;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.messaging.Message;
import com.liferay.portal.kernel.messaging.MessageListenerException;
import com.liferay.portlet.journal.messaging.CheckArticleMessageListener;
import org.junit.BeforeClass;

public class CheckArticleMessageListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CheckArticleMessageListener checkArticleMessageListener0 = new CheckArticleMessageListener();
      Message message0 = new Message();
      try {
        checkArticleMessageListener0.receive(message0);
        fail("Expecting exception: MessageListenerException");
      } catch(MessageListenerException e) {
        /*
         * com.liferay.portal.kernel.bean.BeanLocatorException: BeanLocator has not been set
         */
      }
  }
}
