/*
 * This file was automatically generated by EvoSuite
 */

package org.quickserver.net.server;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.quickserver.net.server.ClientEvent;

public class ClientEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ClientEvent clientEvent0 = ClientEvent.MAX_CON_BLOCKING;
      String string0 = clientEvent0.toString();
      assertEquals("(ClientEvent-Max Connection Blocking)", string0);
  }
}
