/*
 * This file was automatically generated by EvoSuite
 */

package org.quickserver.net.server;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class QuickAuthenticatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 

}
